<h1>Introduccion a numpy</h1>
<img src="https://unipython.com/wp-content/uploads/2017/06/NumPy-Funciones-basicas-de-algebra-496x306.png">

In [1]:
import numpy as np #importamos modulo numpy y lo definimos como np
print("La version es:",np.__version__)
type(np) #tipo de dato
import time

La version es: 1.17.3


In [ ]:
help(np) #ayuda en numpy

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

NumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices. El ancestro de NumPy, Numeric, fue creado originalmente por Jim Hugunin con algunas contribuciones de otros desarrolladores. En 2005, Travis Oliphant creó NumPy incorporando características de Numarray en NumPy con algunas modificaciones. NumPy es open source.

¿Porque utilizar numpy?
La respuesta a grosso modo, vendría dada por el más que discutible rendimiento del lenguaje de programación Python a la hora de llevar a cabo cálculos numéricos.

In [3]:
test_list = list(range(1001))

%timeit sum(test_list)

5.62 µs ± 316 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
test_array = np.arange(1001)

%timeit np.sum(test_array)

3.96 µs ± 232 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Desventajas:
En una misma lista podemos almacenar números enteros, cadenas de texto, números decimales y valores lógicos sin problema alguno. No obstante, todos los elementos de un array de NumPy, obligatoriamente, deben pertenecer al mismo tipo. Por otro lado, estamos acostumbrados a ampliar o reducir el tamaño de una lista en Python de manera dinámica, mientras que en NumPy tendremos que trabajar con arrays de dimensión fija preestablecida. Esto último no es del todo cierto, pero reajustar el tamaño de un array en NumPy no es una operación eficiente, por lo que no se suele realizar salvo contadas excepciones.

Ahora si comencemos.

Creemos un arrreglo que es un objeto de la libreria numpy de tipo array

In [5]:
xa=np.array([1,2,3,4,5]) 
print(xa) #note que los elementos no estan separados por comas
print("tipo de arreglo",type(xa))
print("tipo de datos del arreglo",xa.dtype)
print("primer elemento en arreglo",xa[0])

print("\n")
xl=[1,2,3,4,5]
print(xl) #note que los elementos estan separados por comas
print("tipo de lista",type(xl))
print("primer elemento en lista",xl[0])

[1 2 3 4 5]
tipo de arreglo <class 'numpy.ndarray'>
tipo de datos del arreglo int64
primer elemento en arreglo 1


[1, 2, 3, 4, 5]
tipo de lista <class 'list'>
primer elemento en lista 1


Veamos otro ejemplo relacionado con el tiempo de ejecucion:

In [7]:
tamaño=10000

start=time.time() #reinciar el tiempo
xl=range(tamaño)
yl=range(tamaño)
result=[(x+y) for x,y in zip(xl,yl)]
#print(result)
print("tiempo listas",(time.time()-start)*1000)

start=time.time() #reinciar el tiempo
xa=np.arange(tamaño) #matriz con 10000 elementos 
ya=np.arange(tamaño)
result= xa+ya
#print(result)
print("tiempo numpy",(time.time()-start)*1000)
#de lo anterior se puede ver que es mucho mas rapido realizar operaciones con el modulo NUMPY

tiempo listas 3.353118896484375
tiempo numpy 0.9357929229736328


<h3>Aplicacion de la funcion array al objeto np</h3>

In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

<b>np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0) --> Crea un array.</b>

Los Parametros son:<br>
Objeto:Es el arreglo que queremos realizar<br>
dtype:(obcional)define el tipo de datos que contiene el arreglo por ejempo: puede ser int, float, double, etc.<br>
copy=(obcional)es un booleano puede ser True o False. Si es True el objeto es copiado.<br>
order=(obcional)especifica el diseño de memoria de la matriz.<br>
subok=(opcional) es un booleano y se utiliza si se van a pasar subclases.<br>
ndim=(opcional) es un entero int, especifica el numero menor de dimensiones que el array debe tener.<br>

<h3>El metodo shape y ndim en matrices</h3>

In [11]:
escalar=np.array(2)
print(escalar)
print('Tamaño o shape de escalar: ', escalar.shape)
print('Dimension de escalar: ', escalar.ndim)

print("\n")

x=np.array([1,2,3,4,5]) #esto es un vector columna y su dimension 1
print(x)
print('Tamaño o shape de x: ', x.shape)
print('Dimension de x: ', x.ndim)

print("\n")

y=np.array([[1,2,3],[4,5,6]])
print(y)
print('Tamaño o shape de y: ', y.shape)
print('Dimension de y: ', y.ndim)

print("\n")

z=np.array([[[1,2,3]],[[4,5,6]]])
print(z)
print('Tamaño o shape de z: ', z.shape)
print('Dimension de z: ', z.ndim)

print("\n")

w=np.array([1,2,3,4,5])
print(w)
print('Tamaño o shape de w: ', w.shape)
print('Dimension de w: ', w.ndim)
print("\n")
w.shape=(5,1) #redefinimos tamaño con el metodo shape
print(w)
print('Tamaño o shape de w: ', w.shape)
print('Dimension de w: ', w.ndim)
print("\n")
w.shape=(1,5)
print(w)
print('Tamaño o shape de w: ', w.shape)
print('Dimension de w: ', w.ndim)

2
Tamaño o shape de escalar:  ()
Dimension de escalar:  0


[1 2 3 4 5]
Tamaño o shape de x:  (5,)
Dimension de x:  1


[[1 2 3]
 [4 5 6]]
Tamaño o shape de y:  (2, 3)
Dimension de y:  2


[[[1 2 3]]

 [[4 5 6]]]
Tamaño o shape de z:  (2, 1, 3)
Dimension de z:  3


[1 2 3 4 5]
Tamaño o shape de w:  (5,)
Dimension de w:  1


[[1]
 [2]
 [3]
 [4]
 [5]]
Tamaño o shape de w:  (5, 1)
Dimension de w:  2


[[1 2 3 4 5]]
Tamaño o shape de w:  (1, 5)
Dimension de w:  2


<b>Note lo siguiente</b><br>
-un arreglo 1D es numpy se representa como un vector columna y su tamaño no nos muestra
que solo tenga una columna pues solo muestra el numero de filas, a veces para evitar problemas es necesario
reorganizar para obtener su tamaño de manera de vector columna de tamaño (filas*columnas)<br>
-Los arreglos en numpy pueden ir desde 0 dimensiones (escalar), 1D (vector columna), 2D (matriz), 3D (cubo), 4D(tensor rango 4),
ND(tensor rango N) estas dimensiones estan especificadas por los corchetes que se abren.

<h3>Generar o inicializar matrices variables:</h3>


In [12]:
unos=np.ones((2,2)) #ingresamos el tamaño de la matriz que contiene solo unos, ojo el argumento que recibe es una tupla
print("matriz de unos\n",unos)

print("\n")

ceros=np.zeros((3,3))
print("matriz de ceros\n",ceros)

print("\n")

vectorunos=np.ones((5))
print("vector de unos\n",vectorunos)

print("\n")

identidad1=np.eye(5) #el parametro es el tamaño de la matriz recuerde que es cuadrada
print("matriz identidad\n",identidad1)

print("\n")

identidad2 = np.identity(5)
print("matriz identidad\n",identidad2)

print("\n")

unsolovalor=np.full((2,2),4) #los parametros son tupla de tamaño y elemento de la matriz
print("matriz de un solo valor\n", unsolovalor)

print("\n")

matrizvacia=np.empty((4,4))
print("matriz vacia\n",matrizvacia)

print("\n")

x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matriz x\n",x)
print("\n")
print("Aplicando metodo ones_like\n")
x=np.ones_like(x)
print("matriz x\n",x)
print("\n")
print("Aplicando metodo zeros_like\n")
x=np.zeros_like(x)
print("matriz x\n",x)
print("\n")
print("Aplicando metodo full_like\n")
x=np.full_like(x,7)
print("matriz x\n",x)

matriz de unos
 [[1. 1.]
 [1. 1.]]


matriz de ceros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


vector de unos
 [1. 1. 1. 1. 1.]


matriz identidad
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


matriz identidad
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


matriz de un solo valor
 [[4 4]
 [4 4]]


matriz vacia
 [[4.65601144e-310 1.75300433e+243 4.07192622e+223 2.47326223e+097]
 [1.85722876e-152 2.60985699e+180 6.51842386e+265 9.22948754e+135]
 [4.73517493e-120 4.82336277e+228 1.97387509e-153 4.88701799e+199]
 [6.32672818e+180 4.74483502e+170 9.75018641e-072 4.65587096e-310]]


matriz x
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Aplicando metodo ones_like

matriz x
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


Aplicando metodo zeros_like

matriz x
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


Aplicando metodo full_like

matriz x
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


<b>Otros metodos interesantes:</b><br>
numpy.copy <br>
numpy.asmatrix<br>
numpy.diag<br>
numpy.diagflat<br>
numpy.tri <br>
numpy.tril<br>
numpy.triu<br>

<h3>Convertir parametro de entrada a array(muy importante)</h3>

In [13]:
l=[12,3,4,5,6]
print("lista",l)
print("tipo",type(l))
arreglo=np.asarray(l)
print("arreglo",arreglo)
print("tipo",type(arreglo))
print(arreglo.shape)
print(arreglo.ndim)
print("\n")
print("otro ejemplo")
l=[[1,2],[3,4]]
print("lista",l)
print("tipo",type(l))
arreglo=np.asarray(l)
print("arreglo",arreglo)
print("tipo",type(arreglo))
print(arreglo.shape)
print(arreglo.ndim)

lista [12, 3, 4, 5, 6]
tipo <class 'list'>
arreglo [12  3  4  5  6]
tipo <class 'numpy.ndarray'>
(5,)
1


otro ejemplo
lista [[1, 2], [3, 4]]
tipo <class 'list'>
arreglo [[1 2]
 [3 4]]
tipo <class 'numpy.ndarray'>
(2, 2)
2


<h3>Generar vector columna o rangos numericos con metodos de numpy</h3>

In [15]:
rango1 = np.linspace(0,2,5) #los parametros son valor inicial, valor final y numeros de valores
print(rango1)
print(rango1.shape)
print(rango1.ndim)

print("\n")

rango2 = np.arange(0,30,5) #los parametros son valor inicial,valor final y salto
print(rango2)
print(rango2.shape)
print(rango2.ndim)

print("\n")
 
rango3=np.logspace(0,10,5) #los parametros son valor inicial,valor final y numeros de valores (escala logaritmica)
print(rango3)
print(rango3.shape)
print(rango3.ndim)

print("\n")

rango4=np.geomspace(1,10000,5)
print(rango4)
print(rango4.shape)
print(rango4.ndim)

print("\n")

x = np.linspace(0, 4, 4)
y = np.linspace(0, 3, 3)
print("x",x)
print("y",y)

print("\n")
print("Meshgrid sirve para productos cartesianos\n")
print("Meshgrid es muy útil para evaluar funciones en una cuadrícula\n")

xv, yv = np.meshgrid(x,y) #primer argumento columnas y segundo argumento filas, el resultado son dos arrays
print(xv)
print(xv.shape)
print(xv.ndim)
print(yv)
print(yv.shape)
print(yv.ndim)

x = np.arange(1,7,1)
print("x",x)
print("\n")
print("Meshgrid sirve para productos cartesianos\n")
xv, yv = np.meshgrid(x,x) #primer argumento columnas y segundo argumento filas, el resultado son dos arrays
print(xv)
print(xv.shape)
print(xv.ndim)
print(yv)
print(yv.shape)
print(yv.ndim)

[0.  0.5 1.  1.5 2. ]
(5,)
1


[ 0  5 10 15 20 25]
(6,)
1


[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
(5,)
1


[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
(5,)
1


x [0.         1.33333333 2.66666667 4.        ]
y [0.  1.5 3. ]


Meshgrid sirve para productos cartesianos

Meshgrid es muy útil para evaluar funciones en una cuadrícula

[[0.         1.33333333 2.66666667 4.        ]
 [0.         1.33333333 2.66666667 4.        ]
 [0.         1.33333333 2.66666667 4.        ]]
(3, 4)
2
[[0.  0.  0.  0. ]
 [1.5 1.5 1.5 1.5]
 [3.  3.  3.  3. ]]
(3, 4)
2
x [1 2 3 4 5 6]


Meshgrid sirve para productos cartesianos

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
(6, 6)
2
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]
 [5 5 5 5 5 5]
 [6 6 6 6 6 6]]
(6, 6)
2


<h3>Generar o inicializar matrices aleatorias:</h3>

Distribucion Uniforme:<br>
Devuelve flotantes aleatorios en el intervalo medio abierto [0.0, 1.0).<br>
Los resultados son de la distribución "uniforme continuo" durante el intervalo establecido.

In [16]:
uniforme01=np.random.random((5,4)) #los parametros son el tamaño de la matriz
print(uniforme01)

[[0.97895062 0.3720231  0.10132304 0.18611709]
 [0.57540219 0.86990424 0.46688513 0.04906512]
 [0.48942819 0.63040731 0.57727046 0.62492893]
 [0.12119493 0.32227599 0.44820914 0.55454969]
 [0.27160012 0.54954162 0.51031011 0.13046986]]


Para muestrear Unif [a, b), b> a, multiplique la salida por (b-a) y agregue a :<br>
( b  -  a )  *  random_sample ()  +  a

In [17]:
#distribucion uniforme entre [0,100)
uniformemues=100*np.random.random((5,4)) 
print(uniformemues)

[[89.50162209  1.27218091 16.12219174 74.95756791]
 [11.89130068 69.66294879 34.80564791 94.35702781]
 [67.47947446 35.09534416 21.33416407 80.1212873 ]
 [38.44936497 88.27244506 77.98933672 19.13520171]
 [37.73571649 32.59577025 97.81073637 27.69259302]]


Devuelve enteros aleatorios de bajo (inclusivo) a alto (exclusivo).<br>
numpy.random.randint( bajo , alto = Ninguno , tamaño = Ninguno , dtype = 'l' ) <br>

Devuelve enteros aleatorios de la distribución "uniforme discreta" del tipo especificado en el intervalo "medio<br> abierto" [ bajo , alto ). Si alto es Ninguno (el valor predeterminado), 
los resultados son de [0, bajo ).

In [18]:
unifomeint=np.random.randint(5,10,(5,4))
print(unifomeint)

print("\n")

unifomeint=np.random.randint(25,None,(5,4))
print(unifomeint)

[[8 9 7 8]
 [5 7 8 5]
 [8 9 9 7]
 [8 7 9 6]
 [7 9 5 7]]


[[21  2 17  1]
 [21  9  0 19]
 [ 8 12  0 15]
 [ 0  4  8 15]
 [20  5 23 16]]


Distribucion normal:<br>
Devuelva una muestra (o muestras) de la distribución "normal estándar".
distribución univariada "normal" (gaussiana) de  media 0 y varianza 1 

In [19]:
normal=np.random.randn(3,3) #mu=0 y sigma=1
print(normal)

[[-0.76434862  0.81355335  1.17377424]
 [ 0.77685422 -0.37854123 -0.06879052]
 [ 0.71456474  1.38491551  1.52821221]]


Para muestras aleatorias con mu y sigam determinado , use:<br>

sigma * np.random.randn(...) + mu

In [20]:
normal=2.5*np.random.randn(3,3)+3 #sigma=2.5 y mu=3
print(normal)

[[ 1.96030961  0.65343019  3.42082428]
 [ 3.72297293  2.11363415  4.79786915]
 [-1.62495792  1.54249112  5.27021601]]


<h3>Accediendo a los elementos de un array:</h3>

División de arreglos con NumPy<br>
La división de arreglos es el proceso de extracción de un subconjunto de una de un arreglo determinada. Puedes dividir un arreglo utilizando el operador de dos puntos (:) y especificar el inicio y el final del índice del arreglo, por ejemplo:<br>

array[(filas)from:to:salto,(columnas)from:to:salto]

In [24]:
a=np.random.random((5,5)) 
print("matriz\n",a)
print("\n")
print("indices\n",a[:,:])
print("\n")
print("indices en filas\n",a[1:3,:])
print("\n")
print("indices en filas con saltos\n",a[0:5:2,:])#con saltos
print("\n")
print("indices en columnas\n",a[:,1:3])
print("\n")
print("indices en columnas con saltos\n",a[:,0:5:2])#con saltos
print("\n")
print("indice hasta ultima fila y columna\n",a[0:-1,0:-1])
print("\n")
print("ultima columna\n",a[:,-1])
print("\n")
print("ultima fila\n",a[-1,:])
print("\n")
print("matriz sin ultima columna\n",a[:,:-1])
print("\n")
print("matriz sin primera columna\n",a[:,1:])
print("\n")
print("indices en filas y columnas con saltos\n",a[0:5:2,0:5:2])#con saltos
print("\n")
print("indices seleccionando columna\n",a[:,[1,3,4]])#seleccionando columna

matriz
 [[0.07188673 0.47633593 0.91232111 0.22056415 0.22420516]
 [0.27478571 0.92410564 0.01291854 0.32053642 0.28112364]
 [0.38271885 0.41483983 0.20846896 0.42200806 0.34710629]
 [0.28635736 0.85283999 0.91698565 0.87043432 0.98307552]
 [0.08276672 0.00314794 0.36879089 0.83904393 0.38075655]]


indices
 [[0.07188673 0.47633593 0.91232111 0.22056415 0.22420516]
 [0.27478571 0.92410564 0.01291854 0.32053642 0.28112364]
 [0.38271885 0.41483983 0.20846896 0.42200806 0.34710629]
 [0.28635736 0.85283999 0.91698565 0.87043432 0.98307552]
 [0.08276672 0.00314794 0.36879089 0.83904393 0.38075655]]


indices en filas
 [[0.27478571 0.92410564 0.01291854 0.32053642 0.28112364]
 [0.38271885 0.41483983 0.20846896 0.42200806 0.34710629]]


indices en filas con saltos
 [[0.07188673 0.47633593 0.91232111 0.22056415 0.22420516]
 [0.38271885 0.41483983 0.20846896 0.42200806 0.34710629]
 [0.08276672 0.00314794 0.36879089 0.83904393 0.38075655]]


indices en columnas
 [[0.47633593 0.91232111]
 [0.9241

<h3>Modificaciones en una matriz: (transponer, cambiar tamaño, cambiar dimensiones, intercambiar ejes, unir matrices, etc)</h3>

Reshape: Consiste en reorganizar el tamaño de la matriz sin alterar la dimension de la matriz<br>
numpy.reshape(a, newshape, order='C')

In [26]:
matriz=np.random.random((5,4))
print("matriz\n", matriz)
print('Tamaño o shape de matriz: ', matriz.shape)
print('Dimension de matriz: ', matriz.ndim)

print("\n")

matriz=np.reshape(matriz,(10,2))
print("matriz despues de reshape\n", matriz)
print('Tamaño o shape de matriz: ', matriz.shape)
print('Dimension de matriz: ', matriz.ndim)

print("\n")

vector=np.array([1,2,3,4,5,6,7]
               )
print("vector columna\n", vector)
print('Tamaño o shape de vector: ', vector.shape)
print('Dimension de vector: ', vector.ndim)
vector=np.reshape(vector,(7,1))
print("\n")
print("vector columna despues de reshape\n", vector)
print('Tamaño o shape de vector: ', vector.shape)
print('Dimension de vector: ', vector.ndim)

print("\n")

x=np.arange(6).reshape((2,3))
print("x\n",x)
print(x.shape)
print(x.ndim)

print("\n")

aplanar=x.flatten()
print("aplanar\n",aplanar)
print(aplanar.shape)
print(aplanar.ndim)

print("\n")

xtranp=x.T #transpuesta de x
print("transpuesta de x\n",xtranp)
print(xtranp.shape)
print(xtranp.ndim)

matriz
 [[0.03398132 0.4002696  0.00328486 0.72174299]
 [0.64809785 0.99481999 0.96177997 0.58473685]
 [0.40265317 0.76292416 0.55700467 0.8761262 ]
 [0.63078031 0.48496585 0.87152708 0.87893691]
 [0.21621295 0.58031988 0.43311775 0.65375659]]
Tamaño o shape de matriz:  (5, 4)
Dimension de matriz:  2


matriz despues de reshape
 [[0.03398132 0.4002696 ]
 [0.00328486 0.72174299]
 [0.64809785 0.99481999]
 [0.96177997 0.58473685]
 [0.40265317 0.76292416]
 [0.55700467 0.8761262 ]
 [0.63078031 0.48496585]
 [0.87152708 0.87893691]
 [0.21621295 0.58031988]
 [0.43311775 0.65375659]]
Tamaño o shape de matriz:  (10, 2)
Dimension de matriz:  2


vector columna
 [1 2 3 4 5 6 7]
Tamaño o shape de vector:  (7,)
Dimension de vector:  1


vector columna despues de reshape
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
Tamaño o shape de vector:  (7, 1)
Dimension de vector:  2


x
 [[0 1 2]
 [3 4 5]]
(2, 3)
2


aplanar
 [0 1 2 3 4 5]
(6,)
1


transpuesta de x
 [[0 3]
 [1 4]
 [2 5]]
(3, 2)
2


Intercambiando ejes

In [28]:
uniforme01=np.random.random((2,5,4)) 
print("matriz\n",uniforme01)
print(uniforme01.shape)
print(uniforme01.ndim)
print("\n")
print("aplicamos cambio de ejes")
a=np.moveaxis(uniforme01,0,2)
print("matriz resultante\n",a)
print(a.shape)
print(a.ndim)
print("\n")
uniforme02=np.random.random((5,4))
print("matriz\n",uniforme02)
print(uniforme02.shape)
print(uniforme02.ndim)
print("\n")
print("aplicamos cambio de ejes")
b=np.moveaxis(uniforme02,1,0)# = uniforme02.T , es decir, es igual a sacar la transpuesta.
print("matriz resultante\n",b)
print(b.shape)
print(b.ndim)

matriz
 [[[0.28602647 0.84458636 0.58297782 0.30010041]
  [0.65067255 0.76508133 0.66169094 0.05634608]
  [0.24066243 0.732833   0.82396778 0.54864947]
  [0.18245893 0.73902062 0.74148229 0.11814121]
  [0.95642213 0.68642252 0.22880229 0.58357153]]

 [[0.61881889 0.72962787 0.38069975 0.39018583]
  [0.36229362 0.05370997 0.59158784 0.10149514]
  [0.31428575 0.49911461 0.4736739  0.64758897]
  [0.50442865 0.61346213 0.67725947 0.19456652]
  [0.6930479  0.85456967 0.80245991 0.52734306]]]
(2, 5, 4)
3


aplicamos cambio de ejes
matriz resultante
 [[[0.28602647 0.61881889]
  [0.84458636 0.72962787]
  [0.58297782 0.38069975]
  [0.30010041 0.39018583]]

 [[0.65067255 0.36229362]
  [0.76508133 0.05370997]
  [0.66169094 0.59158784]
  [0.05634608 0.10149514]]

 [[0.24066243 0.31428575]
  [0.732833   0.49911461]
  [0.82396778 0.4736739 ]
  [0.54864947 0.64758897]]

 [[0.18245893 0.50442865]
  [0.73902062 0.61346213]
  [0.74148229 0.67725947]
  [0.11814121 0.19456652]]

 [[0.95642213 0.6930479 ]


Metodo para subir de dimension

In [29]:
a=np.array(2)
print("matriz\n",a)
print(a.shape)
print(a.ndim)
print("\n")
print("subamos dimension")
print("\n")
vector=np.atleast_1d(a)
print("matriz\n",vector)
print(vector.shape)
print(vector.ndim)

matriz
 2
()
0


subamos dimension


matriz
 [2]
(1,)
1


Eliminar entradas unidimensionales

In [31]:
a=np.array([[1,2,3,4,5]])
print("matriz\n",a)
print(a.shape)
print(a.ndim)
a=np.squeeze(a)
print("matriz\n",a)
print(a.shape)
print(a.ndim)

matriz
 [[1 2 3 4 5]]
(1, 5)
2
matriz
 [1 2 3 4 5]
(5,)
1


<img src="https://claudiovz.github.io/scipy-lecture-notes-ES/_images/reductions.png">

Unir matrices

In [36]:
a=np.random.random((5,4))
print("matriz\n",a)
print(a.shape)
print(a.ndim)
print("\n")
b=np.random.random((5,4))
print("matriz\n",b)
print(b.shape)
print(b.ndim)
print("\n")
print("Concatenando filas de ambas matrices\n")
c=np.concatenate((a,b),axis=0) #une filas
print("matriz\n",c)
print(c.shape)
print(c.ndim)
print("\n")
print("Concatenando columnas de ambas matrices\n")
d=np.concatenate((a,b),axis=1) #une columnas
print("matriz\n",d)
print(d.shape)
print(d.ndim)

matriz
 [[0.09017955 0.26292722 0.32843655 0.42060982]
 [0.24679005 0.10602521 0.93077537 0.39854609]
 [0.75442619 0.99954125 0.26425824 0.7736578 ]
 [0.41765501 0.81205657 0.54182213 0.63928618]
 [0.04821613 0.12717464 0.42633254 0.12976023]]
(5, 4)
2


matriz
 [[0.1291825  0.77557456 0.42252674 0.49723376]
 [0.84993461 0.4317725  0.94672871 0.73862626]
 [0.82762277 0.4503417  0.64097761 0.29795592]
 [0.62820634 0.27340759 0.21463865 0.77101212]
 [0.81678297 0.6125197  0.59664087 0.35768226]]
(5, 4)
2


Concatenando filas de ambas matrices

matriz
 [[0.09017955 0.26292722 0.32843655 0.42060982]
 [0.24679005 0.10602521 0.93077537 0.39854609]
 [0.75442619 0.99954125 0.26425824 0.7736578 ]
 [0.41765501 0.81205657 0.54182213 0.63928618]
 [0.04821613 0.12717464 0.42633254 0.12976023]
 [0.1291825  0.77557456 0.42252674 0.49723376]
 [0.84993461 0.4317725  0.94672871 0.73862626]
 [0.82762277 0.4503417  0.64097761 0.29795592]
 [0.62820634 0.27340759 0.21463865 0.77101212]
 [0.81678297 0.612519

Dividir matrices

In [40]:
a=np.random.random((5,4))
print("matriz\n",a)
print(a.shape)
print(a.ndim)
print("\n")
print("Dividiendo filas de la matriz con metodo split\n")
d,c,f,g,h=np.split(a,[1,2,3,4],axis=0)
print("matriz\n",d)
print("\n")
print("matriz\n",c)
print("\n")
print("matriz\n",f)
print("\n")
print("matriz\n",g)
print("\n")
print("matriz\n",h)
print("\n")
print("Dividiendo columnas de la matriz con metodo split\n")
d,c,f,g=np.split(a,[1,2,3],axis=1)
print("matriz\n",d)
print("\n")
print("matriz\n",c)
print("\n")
print("matriz\n",f)
print("\n")
print("matriz\n",g)

matriz
 [[0.60833172 0.66431175 0.98964031 0.09198052]
 [0.19806928 0.70303471 0.69100005 0.40280155]
 [0.2503636  0.8710737  0.54080236 0.0989106 ]
 [0.9791072  0.09960679 0.63289652 0.34091179]
 [0.40080311 0.98336089 0.44552986 0.8289414 ]]
(5, 4)
2


Dividiendo filas de la matriz con metodo split

matriz
 [[0.60833172 0.66431175 0.98964031 0.09198052]]


matriz
 [[0.19806928 0.70303471 0.69100005 0.40280155]]


matriz
 [[0.2503636  0.8710737  0.54080236 0.0989106 ]]


matriz
 [[0.9791072  0.09960679 0.63289652 0.34091179]]


matriz
 [[0.40080311 0.98336089 0.44552986 0.8289414 ]]


Dividiendo columnas de la matriz con metodo split

matriz
 [[0.60833172]
 [0.19806928]
 [0.2503636 ]
 [0.9791072 ]
 [0.40080311]]


matriz
 [[0.66431175]
 [0.70303471]
 [0.8710737 ]
 [0.09960679]
 [0.98336089]]


matriz
 [[0.98964031]
 [0.69100005]
 [0.54080236]
 [0.63289652]
 [0.44552986]]


matriz
 [[0.09198052]
 [0.40280155]
 [0.0989106 ]
 [0.34091179]
 [0.8289414 ]]


Repetir elementos

In [43]:
a=np.random.random((5,4))
print("matriz\n",a)
print(a.shape)
print(a.ndim)
print("\n")
print("Repitiendo columnas con metodo tile\n")
b=np.tile(a,3) #permite repetir solo en columnas 3 veces
print("matriz\n",b)
print(b.shape)
print(b.ndim)
print("\n")
print("Repitiendo filas o columnas con metodo repeat\n")
c=np.repeat(a,3,axis=1) #permite repetir en columnas o filas 3 veces en este caso 
print("matriz\n",c)
print(c.shape)
print(c.ndim)

matriz
 [[0.95041344 0.5061336  0.21017438 0.27426642]
 [0.22071857 0.49605379 0.90762396 0.20763916]
 [0.2891101  0.37043821 0.69678672 0.56336927]
 [0.86644206 0.87202799 0.28434959 0.57605577]
 [0.00313623 0.31348122 0.54970276 0.56948949]]
(5, 4)
2


Repitiendo columnas con metodo tile

matriz
 [[0.95041344 0.5061336  0.21017438 0.27426642 0.95041344 0.5061336
  0.21017438 0.27426642 0.95041344 0.5061336  0.21017438 0.27426642]
 [0.22071857 0.49605379 0.90762396 0.20763916 0.22071857 0.49605379
  0.90762396 0.20763916 0.22071857 0.49605379 0.90762396 0.20763916]
 [0.2891101  0.37043821 0.69678672 0.56336927 0.2891101  0.37043821
  0.69678672 0.56336927 0.2891101  0.37043821 0.69678672 0.56336927]
 [0.86644206 0.87202799 0.28434959 0.57605577 0.86644206 0.87202799
  0.28434959 0.57605577 0.86644206 0.87202799 0.28434959 0.57605577]
 [0.00313623 0.31348122 0.54970276 0.56948949 0.00313623 0.31348122
  0.54970276 0.56948949 0.00313623 0.31348122 0.54970276 0.56948949]]
(5, 12)
2


Rep

Añadiendo y removiendo elementos

In [47]:
a=np.random.random((5,4))
print("matriz\n",a)
print(a.shape)
print(a.ndim)
print("\n")
print("Utilizando metodo delete para borrar una fila de la matriz\n")
b=np.delete(a,[1],axis=0)#borra fila 1
print("matriz\n",b)
print(b.shape)
print(b.ndim)
print("\n")
print("Utilizando metodo delete para borrar una columna de la matriz\n")
c=np.delete(a,[3],axis=1) #borra columna 4
print("matriz\n",c)
print(c.shape)
print(c.ndim)
print("\n")
print("Utilizando metodo delete para borrar varias filas de la matriz\n")
d=np.delete(a,[0,1],axis=0) #borra fila 0 y 1
print("matriz\n",d)
print(d.shape)
print(d.ndim)
print("\n")
fila=np.array([1,2,3,4]).reshape(1,4)
print("fila\n",fila)
print(fila.shape)
print(fila.ndim)
print("\n")
columna=np.array([1,2,3,4,5]).reshape(5)
print("columna\n",columna)
print(columna.shape)
print(columna.ndim)
print("\n")
print("Utilizando metodo insert para añadir fila a una posicion de la matriz\n")
e=np.insert(a,2,fila,axis=0) #añadimos fila
print("matriz\n",e)
print(e.shape)
print(e.ndim)
print("\n")
print("Utilizando metodo insert para añadir columna a una posicion de la matriz\n")
f=np.insert(a,1,columna,axis=1)#añadimo columna
print("matriz\n",f)
print(f.shape)
print(f.ndim)
print("\n")
print("Utilizando metodo append para añadir columna al final de la matriz\n")
columna=np.array([1,2,3,4,5]).reshape(5,1)
g=np.append(a,columna,axis=1)#añadimos columna al final
print("matriz\n",g)
print(g.shape)
print(g.ndim)
print("\n")
print("Utilizando metodo append para añadir fila al final de la matriz\n")
h=np.append(a,fila,axis=0)#añadimos fila al final
print("matriz\n",h)
print(h.shape)
print(h.ndim)

matriz
 [[0.73770935 0.19854985 0.4439638  0.77378423]
 [0.23518484 0.84943888 0.08774846 0.17070586]
 [0.26628066 0.4870355  0.55071718 0.44388272]
 [0.31629548 0.58533345 0.47595038 0.43854858]
 [0.00868594 0.31095271 0.66665487 0.32071437]]
(5, 4)
2


Utilizando metodo delete para borrar una fila de la matriz

matriz
 [[0.73770935 0.19854985 0.4439638  0.77378423]
 [0.26628066 0.4870355  0.55071718 0.44388272]
 [0.31629548 0.58533345 0.47595038 0.43854858]
 [0.00868594 0.31095271 0.66665487 0.32071437]]
(4, 4)
2


Utilizando metodo delete para borrar una columna de la matriz

matriz
 [[0.73770935 0.19854985 0.4439638 ]
 [0.23518484 0.84943888 0.08774846]
 [0.26628066 0.4870355  0.55071718]
 [0.31629548 0.58533345 0.47595038]
 [0.00868594 0.31095271 0.66665487]]
(5, 3)
2


Utilizando metodo delete para borrar varias filas de la matriz

matriz
 [[0.26628066 0.4870355  0.55071718 0.44388272]
 [0.31629548 0.58533345 0.47595038 0.43854858]
 [0.00868594 0.31095271 0.66665487 0.32071437]]


<h3>Operaciones entre matrices:</h3>

Las operaciones matemáticas entre arrays en NumPy se suelen llevar a cabo elemento por elemento por lo que debemos ser cautos con las dimensiones de los arrays implicados en la operación.<br>

Algunas de las operaciones son:<br>
np.sum()<br>
np.mean()<br>
np.std()<br>
np.var()<br>
np.min()<br>
np.max()<br>
np.argmin()<br>
np.argmax()<br>

Calcular la suma, resta, multiplicación y división de dos matrices

In [48]:
x= np.array([(1,2,3),(3,4,5)])
print("x\n",x)
y= np.array([(1,2,3),(3,4,5)])
print("y\n",y)
print("\n")
print("suma matrices\n",x+y)
print("\n")
print("resta matrices\n",x-y)
print("\n")
print("multiplicacion elemento a elemento \n",x*y)
print("\n")
print("division elemento a elemento\n",x/y)

x
 [[1 2 3]
 [3 4 5]]
y
 [[1 2 3]
 [3 4 5]]


suma matrices
 [[ 2  4  6]
 [ 6  8 10]]


resta matrices
 [[0 0 0]
 [0 0 0]]


multiplicacion elemento a elemento 
 [[ 1  4  9]
 [ 9 16 25]]


division elemento a elemento
 [[1. 1. 1.]
 [1. 1. 1.]]


Elemento minimo, elemento maximo y suma de todos los elementos de una matriz.

In [50]:
a= np.array([2,4,8])
print("matriz\n",a)
print("\n")
print("valor minimo de la matriz\n",a.min())
print("\n")
print("valor maximo de la matriz\n",a.max())
print("\n")
print("suma de todos los elementos\n",a.sum())

matriz
 [2 4 8]


valor minimo de la matriz
 2


valor maximo de la matriz
 8


suma de todos los elementos
 14


Calcular la raíz cuadrada y la desviación estándar

In [52]:
a=np.array([(1,2,3),(3,4,5,)])
print("matriz\n",a)
print("\n")
print("raiz de cada elemento\n",np.sqrt(a))
print("\n")
print("desviacion estandar de todos los elementos de la matriz\n",np.std(a))

matriz
 [[1 2 3]
 [3 4 5]]


raiz de cada elemento
 [[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


desviacion estandar de todos los elementos de la matriz
 1.2909944487358056


Multiplicacion de matrices, determinante e inversa:

In [72]:
a=np.random.random((5,4))
print("matriz A\n",a)
print("\n")
b=np.random.random((4,3))
print("matriz B\n",b)
print("\n")
c=np.dot(a,b)
print("multiplicacion de matrices C=A*B\n",c)
d=np.ones((3,3))
print("\n")
print("matriz D\n",d)
d_1=np.linalg.det(d)
print("determinante de D",d_1)
print("\n")
f=np.identity(3)
print("\n")
print("matriz F\n",f)
h=np.linalg.inv(f)
print("\n")
print("matriz F^-1\n",h)

matriz A
 [[0.92418731 0.7141887  0.61362962 0.01012809]
 [0.69613035 0.02668239 0.46217097 0.97135423]
 [0.09336338 0.52729242 0.01995036 0.39707757]
 [0.10091139 0.4168599  0.93744912 0.04987422]
 [0.39458674 0.7487501  0.95170854 0.77660478]]


matriz B
 [[0.59285668 0.28587166 0.93468481]
 [0.03094483 0.14517837 0.33605734]
 [0.18563478 0.06580567 0.88073543]
 [0.34966171 0.88695459 0.69796279]]


multiplicacion de matrices C=A*B
 [[0.68746347 0.41724717 1.65134657]
 [0.8389716  1.09483821 1.74464873]
 [0.21421438 0.45674402 0.55918217]
 [0.26418792 0.19529238 1.09486418]
 [0.7053225  0.97294448 2.00068187]]


matriz D
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
determinante de D 0.0




matriz F
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


matriz F^-1
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Ordenar arreglos NumPy

Puede ordenar el arreglo NumPy usando el método sort () del módulo NumPy:

La función sort () toma un eje opcional (un entero) que es -1 por defecto. El eje especifica
de acuerdo a qué eje queremos ordenar el arreglo. -1 significa que el arreglo
se ordenará según el último eje.

In [54]:
a = np.array([16, 3, 2, 6, 8, 10, 1])
print("matriz\n",a)
print("\n")
print("Sorted array = ", np.sort(a))

matriz
 [16  3  2  6  8 10  1]


Sorted array =  [ 1  2  3  6  8 10 16]


Normalizar un arreglo:

x = (x – xmin) / (xmax – xmin)

In [58]:
x= np.array([400, 800, 200, 700, 1000, 2000, 300])
print("matriz\n",x)

xmax = x.max()

xmin = x.min()

x = (x - xmin)/(xmax - xmin)
print("\n")
print("After normalization array x = \n", x)

matriz
 [ 400  800  200  700 1000 2000  300]


After normalization array x = 
 [0.11111111 0.33333333 0.         0.27777778 0.44444444 1.
 0.05555556]


Arreglo NumPy a CSV

In [60]:
a = np.array([1, 2, 3, 4, 5])

np.savetxt("myArray.csv", a)

<b>
Que falta analizar
    

brodcasting

operaciones logicas y booleanos

copias de matrices

Entrada de matrices

Funciones para tomar datos de los arreglos

Metodo itemsize

<b>Nota:</b> Durante el desarrollo del estudio de la libreria numpy no estamos teniendo objetos de tipo strin o cadenas de texto en matrices
    las cuales son muy importantes y tienen bastantes aplicaciones en el mundo real.<br>
    Es por esto que se vuelve importante realizar un analisis personal de las rutinas de la biblioteca numpy asociados a string

<b>Constantes en numpy:</b>
    
numpy.Inf

numpy.Infinity

numpy.NAN

numpy.NINF

numpy.NZERO

numpy.NaN

numpy.PINF

numpy.PZERO

numpy.e

numpy.euler_gamma

numpy.inf

numpy.infty

numpy.nan

numpy.newaxis

numpy.pi

<h3>Metodos o Rutinas de numpy especiales para ciertas labores.</h3>

<b>Funciones matematicas de Numpy:</b>

<b>Operaciones Aritmeticas</b>

add(x1, x2, /[, out, where, casting, order, …])	Add arguments element-wise.

reciprocal(x, /[, out, where, casting, …])	Return the reciprocal of the argument, element-wise.

positive(x, /[, out, where, casting, order, …])	Numerical positive, element-wise.

negative(x, /[, out, where, casting, order, …])	Numerical negative, element-wise.

multiply(x1, x2, /[, out, where, casting, …])	Multiply arguments element-wise.

divide(x1, x2, /[, out, where, casting, …])	Returns a true division of the inputs, element-wise.

power(x1, x2, /[, out, where, casting, …])	First array elements raised to powers from second array, element-wise.

subtract(x1, x2, /[, out, where, casting, …])	Subtract arguments, element-wise.

true_divide(x1, x2, /[, out, where, …])	Returns a true division of the inputs, element-wise.

floor_divide(x1, x2, /[, out, where, …])	Return the largest integer smaller or equal to the division of the inputs.

float_power(x1, x2, /[, out, where, …])	First array elements raised to powers from second array, element-wise.

fmod(x1, x2, /[, out, where, casting, …])	Return the element-wise remainder of division.

mod(x1, x2, /[, out, where, casting, order, …])	Return element-wise remainder of division.

modf(x[, out1, out2], / [[, out, where, …])	Return the fractional and integral parts of an array, element-wise.

remainder(x1, x2, /[, out, where, casting, …])	Return element-wise remainder of division.

divmod(x1, x2[, out1, out2], / [[, out, …])	Return element-wise quotient and remainder simultaneously.
          
                                
<b>Funciones Trigonometricas</b> 
                                
sin(x, /[, out, where, casting, order, …])	Trigonometric sine, element-wise.

cos(x, /[, out, where, casting, order, …])	Cosine element-wise.
                                
tan(x, /[, out, where, casting, order, …])	Compute tangent element-wise.

arcsin(x, /[, out, where, casting, order, …])	Inverse sine, element-wise.

arccos(x, /[, out, where, casting, order, …])	Trigonometric inverse cosine, element-wise.

arctan(x, /[, out, where, casting, order, …])	Trigonometric inverse tangent, element-wise.
                                
hypot(x1, x2, /[, out, where, casting, …])	Given the “legs” of a right triangle, return its hypotenuse.
                                
arctan2(x1, x2, /[, out, where, casting, …])	Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
                                
degrees(x, /[, out, where, casting, order, …])	Convert angles from radians to degrees.
                                
radians(x, /[, out, where, casting, order, …])	Convert angles from degrees to radians.
                                
unwrap(p[, discont, axis])	Unwrap by changing deltas between values to 2*pi complement.
                                
deg2rad(x, /[, out, where, casting, order, …])	Convert angles from degrees to radians.
                                
rad2deg(x, /[, out, where, casting, order, …])	Convert angles from radians to degrees.
                                
                                
<b>Funcion exponencial y logaritmos:</b>
                                
exp(x, /[, out, where, casting, order, …])	Calculate the exponential of all elements in the input array.
                                
expm1(x, /[, out, where, casting, order, …])	Calculate exp(x) - 1 for all elements in the array.
                                
exp2(x, /[, out, where, casting, order, …])	Calculate 2**p for all p in the input array.
                                
log(x, /[, out, where, casting, order, …])	Natural logarithm, element-wise.
                                
log10(x, /[, out, where, casting, order, …])	Return the base 10 logarithm of the input array, element-wise.
                                
log2(x, /[, out, where, casting, order, …])	Base-2 logarithm of x.
                                
log1p(x, /[, out, where, casting, order, …])	Return the natural logarithm of one plus the input array, element-wise.

logaddexp(x1, x2, /[, out, where, casting, …])	Logarithm of the sum of exponentiations of the inputs.
                                
logaddexp2(x1, x2, /[, out, where, casting, …])	Logarithm of the sum of exponentiations of the inputs in base-2.
                                
                                
<b>Sums, products, differences</b>
                                
prod(a[, axis, dtype, out, keepdims, …])	Return the product of array elements over a given axis.
                                
sum(a[, axis, dtype, out, keepdims, …])	Sum of array elements over a given axis.
                                
nanprod(a[, axis, dtype, out, keepdims])	Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.

nansum(a[, axis, dtype, out, keepdims])	Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.

cumprod(a[, axis, dtype, out])	Return the cumulative product of elements along a given axis.
                                
cumsum(a[, axis, dtype, out])	Return the cumulative sum of the elements along a given axis.
                                
nancumprod(a[, axis, dtype, out])	Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one.

nancumsum(a[, axis, dtype, out])	Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.

diff(a[, n, axis, prepend, append])	Calculate the n-th discrete difference along the given axis.
                                
ediff1d(ary[, to_end, to_begin])	The differences between consecutive elements of an array.
                                
gradient(f, \*varargs, \*\*kwargs)	Return the gradient of an N-dimensional array.
                                
cross(a, b[, axisa, axisb, axisc, axis])	Return the cross product of two (arrays of) vectors.
                                
trapz(y[, x, dx, axis])	Integrate along the given axis using the composite trapezoidal rule.
                                
                                
<b>Otras funciones:</b>
                                
convolve(a, v[, mode])	Returns the discrete, linear convolution of two one-dimensional sequences.
                                
clip(a, a_min, a_max[, out])	Clip (limit) the values in an array.
                                
sqrt(x, /[, out, where, casting, order, …])	Return the non-negative square-root of an array, element-wise.
                                
cbrt(x, /[, out, where, casting, order, …])	Return the cube-root of an array, element-wise.
                                
square(x, /[, out, where, casting, order, …])	Return the element-wise square of the input.
                                
absolute(x, /[, out, where, casting, order, …])	Calculate the absolute value element-wise.
                                
fabs(x, /[, out, where, casting, order, …])	Compute the absolute values element-wise.
                                
sign(x, /[, out, where, casting, order, …])	Returns an element-wise indication of the sign of a number.
                                
heaviside(x1, x2, /[, out, where, casting, …])	Compute the Heaviside step function.
                                
maximum(x1, x2, /[, out, where, casting, …])	Element-wise maximum of array elements.
                                
minimum(x1, x2, /[, out, where, casting, …])	Element-wise minimum of array elements.
                                
fmax(x1, x2, /[, out, where, casting, …])	Element-wise maximum of array elements.
                                
fmin(x1, x2, /[, out, where, casting, …])	Element-wise minimum of array elements.
                                
nan_to_num(x[, copy, nan, posinf, neginf])	Replace NaN with zero and infinity with large finite numbers (default behaviour) or with the numbers defined by the user using the nan, posinf and/or neginf keywords.

real_if_close(a[, tol])	If complex input returns a real array if complex parts are close to zero.
                                
interp(x, xp, fp[, left, right, period])	One-dimensional linear interpolation.

<b>Algebra lineal</b>

<b>Matrix and vector products</b>

dot(a, b[, out])	Dot product of two arrays.

linalg.multi_dot(arrays)	Compute the dot product of two or more arrays in a single function call, while automatically selecting the fastest evaluation order.

vdot(a, b)	Return the dot product of two vectors.

inner(a, b)	Inner product of two arrays.

outer(a, b[, out])	Compute the outer product of two vectors.

matmul(x1, x2, /[, out, casting, order, …])	Matrix product of two arrays.

tensordot(a, b[, axes])	Compute tensor dot product along specified axes.

einsum(subscripts, *operands[, out, dtype, …])	Evaluates the Einstein summation convention on the operands.

einsum_path(subscripts, *operands[, optimize])	Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.

linalg.matrix_power(a, n)	Raise a square matrix to the (integer) power n.

kron(a, b)	Kronecker product of two arrays.


<b>Decompositions</b>

linalg.cholesky(a)	Cholesky decomposition.

linalg.qr(a[, mode])	Compute the qr factorization of a matrix.

linalg.svd(a[, full_matrices, compute_uv, …])	Singular Value Decomposition.


<b>Matrix eigenvalues</b>

linalg.eig(a)	Compute the eigenvalues and right eigenvectors of a square array.

linalg.eigh(a[, UPLO])	Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.

linalg.eigvals(a)	Compute the eigenvalues of a general matrix.

linalg.eigvalsh(a[, UPLO])	Compute the eigenvalues of a complex Hermitian or real symmetric matrix.


<b>Norms and other numbers</b>

linalg.norm(x[, ord, axis, keepdims])	Matrix or vector norm.

linalg.cond(x[, p])	Compute the condition number of a matrix.

linalg.det(a)	Compute the determinant of an array.

linalg.matrix_rank(M[, tol, hermitian])	Return matrix rank of array using SVD method

linalg.slogdet(a)	Compute the sign and (natural) logarithm of the determinant of an array.

trace(a[, offset, axis1, axis2, dtype, out])	Return the sum along diagonals of the array.


<b>Solving equations and inverting matrices</b>

linalg.solve(a, b)	Solve a linear matrix equation, or system of linear scalar equations.

linalg.tensorsolve(a, b[, axes])	Solve the tensor equation a x = b for x.

linalg.lstsq(a, b[, rcond])	Return the least-squares solution to a linear matrix equation.

linalg.inv(a)	Compute the (multiplicative) inverse of a matrix.

linalg.pinv(a[, rcond, hermitian])	Compute the (Moore-Penrose) pseudo-inverse of a matrix.

linalg.tensorinv(a[, ind])	Compute the ‘inverse’ of an N-dimensional array.

<b>Funciones de estadistica en numpy</b>

<b>Order statistics</b>

amin(a[, axis, out, keepdims, initial, where])	Return the minimum of an array or minimum along an axis.

amax(a[, axis, out, keepdims, initial, where])	Return the maximum of an array or maximum along an axis.

nanmin(a[, axis, out, keepdims])	Return minimum of an array or minimum along an axis, ignoring any NaNs.

nanmax(a[, axis, out, keepdims])	Return the maximum of an array or maximum along an axis, ignoring any NaNs.

ptp(a[, axis, out, keepdims])	Range of values (maximum - minimum) along an axis.

percentile(a, q[, axis, out, …])	Compute the q-th percentile of the data along the specified axis.

nanpercentile(a, q[, axis, out, …])	Compute the qth percentile of the data along the specified axis, while ignoring nan values.

quantile(a, q[, axis, out, overwrite_input, …])	Compute the q-th quantile of the data along the specified axis.

nanquantile(a, q[, axis, out, …])	Compute the qth quantile of the data along the specified axis, while ignoring nan values.


<b>Averages and variances</b>

median(a[, axis, out, overwrite_input, keepdims])	Compute the median along the specified axis.

average(a[, axis, weights, returned])	Compute the weighted average along the specified axis.

mean(a[, axis, dtype, out, keepdims])	Compute the arithmetic mean along the specified axis.

std(a[, axis, dtype, out, ddof, keepdims])	Compute the standard deviation along the specified axis.

var(a[, axis, dtype, out, ddof, keepdims])	Compute the variance along the specified axis.

nanmedian(a[, axis, out, overwrite_input, …])	Compute the median along the specified axis, while ignoring NaNs.

nanmean(a[, axis, dtype, out, keepdims])	Compute the arithmetic mean along the specified axis, ignoring NaNs.

nanstd(a[, axis, dtype, out, ddof, keepdims])	Compute the standard deviation along the specified axis, while ignoring NaNs.

nanvar(a[, axis, dtype, out, ddof, keepdims])	Compute the variance along the specified axis, while ignoring NaNs.


<b>Correlating</b>

corrcoef(x[, y, rowvar, bias, ddof])	Return Pearson product-moment correlation coefficients.

correlate(a, v[, mode])	Cross-correlation of two 1-dimensional sequences.

cov(m[, y, rowvar, bias, ddof, fweights, …])	Estimate a covariance matrix, given data and weights.


<b>Histograms</b>

histogram(a[, bins, range, normed, weights, …])	Compute the histogram of a set of data.

histogram2d(x, y[, bins, range, normed, …])	Compute the bi-dimensional histogram of two data samples.

histogramdd(sample[, bins, range, normed, …])	Compute the multidimensional histogram of some data.

bincount(x[, weights, minlength])	Count number of occurrences of each value in array of non-negative ints.

histogram_bin_edges(a[, bins, range, weights])	Function to calculate only the edges of the bins used by the histogram function.

digitize(x, bins[, right])	Return the indices of the bins to which each value in input array belongs.

<b>Input and output</b>

<b>NumPy binary files (NPY, NPZ)</b>

load(file[, mmap_mode, allow_pickle, …])	Load arrays or pickled objects from .npy, .npz or pickled files.

save(file, arr[, allow_pickle, fix_imports])	Save an array to a binary file in NumPy .npy format.

savez(file, \*args, \*\*kwds)	Save several arrays into a single file in uncompressed .npz format.

savez_compressed(file, \*args, \*\*kwds)	Save several arrays into a single file in compressed .npz format.
The format of these binary file types is documented in numpy.lib.format


<b>Text files</b>

loadtxt(fname[, dtype, comments, delimiter, …])	Load data from a text file.

savetxt(fname, X[, fmt, delimiter, newline, …])	Save an array to a text file.

genfromtxt(fname[, dtype, comments, …])	Load data from a text file, with missing values handled as specified.

fromregex(file, regexp, dtype[, encoding])	Construct an array from a text file, using regular expression parsing.

fromstring(string[, dtype, count, sep])	A new 1-D array initialized from text data in a string.

ndarray.tofile(fid[, sep, format])	Write array to a file as text or binary (default).

ndarray.tolist()	Return the array as an a.ndim-levels deep nested list of Python scalars.


<b>Raw binary files</b>

fromfile(file[, dtype, count, sep, offset])	Construct an array from data in a text or binary file.

ndarray.tofile(fid[, sep, format])	Write array to a file as text or binary (default).


<b>String formatting</b>

array2string(a[, max_line_width, precision, …])	Return a string representation of an array.

array_repr(arr[, max_line_width, precision, …])	Return the string representation of an array.

array_str(a[, max_line_width, precision, …])	Return a string representation of the data in an array.

format_float_positional(x[, precision, …])	Format a floating-point scalar as a decimal string in positional notation.

format_float_scientific(x[, precision, …])	Format a floating-point scalar as a decimal string in scientific notation.


<b>Memory mapping files</b>

memmap	Create a memory-map to an array stored in a binary file on disk.


<b>Text formatting options</b>

set_printoptions([precision, threshold, …])	Set printing options.

get_printoptions()	Return the current print options.

set_string_function(f[, repr])	Set a Python function to be used when pretty printing arrays.

printoptions(\*args, \*\*kwargs)	Context manager for setting print options.


<b>Base-n representations</b>

binary_repr(num[, width])	Return the binary representation of the input number as a string.

base_repr(number[, base, padding])	Return a string representation of a number in the given base system.


<b>Data sources</b>

DataSource([destpath])	A generic data source file (file, http, ftp, …).


<b>Binary Format Description</b>

lib.format	Binary serialization

Hasta aca tenemos el tema de la libreria Numpy, la cual es una de las librerias mas
importantes para algebra lineal. Para una observacion mas detallada de la libreria consultar la referencia de 
Numpy https://docs.scipy.org/doc/numpy/reference/ o routines/metodos de la libreria https://docs.scipy.org/doc/numpy/reference/routines.html.<br>
Si tienes alguna duda no olvides escribir a <br>
<b>andres.programacion123@gmail.com</b>
