# Markdown
## Subtitulo
Texto plano
Negrilla usando **bold** y __bold__. 
Cursiva usando *italic* y _italic_.
Podemos crear una lista:
* Elemento 1
* Elemento 2

Y una lista numerada
1. Número 1
2. Número 2

[Hipervínculo](https://www.udea.edu.co)

Código en la misma línea `foo()`, código en bloque:
```
bar()
```
 ![Otro texto](http://www.udea.edu.co/wps/wcm/connect/udea/abb2bfd3-5e1d-4b6c-ab1f-3addb87b7b22/escudo.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE.Z18_L8L8H8C0LODDC0A6SSS2AD2GO4-abb2bfd3-5e1d-4b6c-ab1f-3addb87b7b22-kMALT8L)

# Python

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
this?

## Variables

In [0]:
print("Hola Mundo") #Esto es un comentario
print('Hola mundo') #Este es otro comentario

Hola Mundo
Hola mundo


In [0]:
time print("Hola") #lo vamos a usar mucho 

Hola
CPU times: user 0 ns, sys: 1.65 ms, total: 1.65 ms
Wall time: 1.37 ms


In [0]:
x='Mundo'
y=1
z=2.0
print(x,type(x))
print(y,type(y))
print(z,type(z))

Mundo <class 'str'>
1 <class 'int'>
2.0 <class 'float'>


In [0]:
x?

In [0]:
x,y,z='Hola',20,30.0
print(x,y,z)

Hola 20 30.0


In [0]:
w=y+z
print(y,z,w,type(w))

20 30.0 50.0 <class 'float'>


In [0]:
w=y/2
print(w,type(w),type(y))
w=y*2
print(w,type(w),type(y))
w=y%3
print(w,type(w),type(y))

10.0 <class 'float'> <class 'int'>
40 <class 'int'> <class 'int'>
2 <class 'int'> <class 'int'>


In [0]:
w=y**2
print(w,type(w))
w=z**2
print(w,type(w))

400 <class 'int'>
900.0 <class 'float'>


In [0]:
x='Hola Mundo'
print(x.upper())
print(x.lower())

HOLA MUNDO
hola mundo


In [0]:
print('Hola '+x)
print('Hola '+str(y))
print('Hola'*y)

Hola Hola Mundo
Hola 20
HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola


## Listas

In [0]:
lista1=[5,4,3,2,1]
print(lista1,type(lista1))
print(lista1[0],lista1[-1])
print(lista1[1:],lista1[1:3])
print(lista1[0:4:2],lista1[::2],lista1[::-1])

[5, 4, 3, 2, 1] <class 'list'>
5 1
[4, 3, 2, 1] [4, 3]
[5, 3] [5, 3, 1] [1, 2, 3, 4, 5]


In [0]:
x='Hola'
print(x[1:])

ola


In [0]:
lista2=[1,2,3,4,5]
print(lista1+lista2)

[5, 4, 3, 2, 1, 1, 2, 3, 4, 5]


In [0]:
print([1,2,3]*4)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [0]:
print(lista1[0])
lista1[0]=0
print(lista1[0])
print(lista1)

0
0
[0, 4, 3, 2, 1]


In [0]:
x='Hola'
print(x[0])
x[0]='P'
print(x[0])

H


TypeError: ignored

In [0]:
y=list(x)
y[0]='P'
''.join(y)

'Pola'

## Diccionarios

In [0]:
x={'num1':3,'num2':2,'num3':1}
print(x,type(x))

{'num1': 3, 'num2': 2, 'num3': 1} <class 'dict'>


In [0]:
print(x.keys())
print(x.items())

dict_keys(['num1', 'num2', 'num3'])
dict_items([('num1', 3), ('num2', 2), ('num3', 1)])


## Condicionales

In [0]:
x=2
print(x<=2)
print(x>4)
print(x!=1)
print(x==2)

True
False
True
True


In [0]:
x=2
y=1 if x<3 else 2
print(y)

1


In [0]:
x,y=21,'Camilo'
print(not x>18)
print(x>=18 and y=='Camilo')
print(x>=18 or y=='Santa')

False
True
True


In [0]:
any([False,True,True])

True

In [0]:
nombres=['Camilo','Santa','Velez']
print('Camilo' in nombres)
print('Edison' in nombres)

True
False


In [0]:
minombre='Jorge'
if minombre in nombres:
      print('Pase')
elif minombre=='Edison':
      print('Hola Edison')
        print('Hola')
else:
      print('Fuera')

Fuera


In [0]:
x=[1,2,3]
y=x
z=[1,2,3]
print(y is x,y==x)
print(z is x,z==x)

True True
False True


## Loops

In [0]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
for x in range(10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [0]:
for x in range(3,10,2):
  print(x)
else:
  print('Listo')

3
5
7
9
Listo


In [0]:
for x in range(10):
  if x==3: continue
  if x==7: break
  print(x)
else:
  print('Listo')

0
1
2
4
5
6


In [0]:
nombres=['Camilo','Santa','Velez']
for x in nombres:
  print(x)

Camilo
Santa
Velez


In [0]:
nombres=['Camilo','Santa','Velez']
for i,x in enumerate(nombres):
  print(i,x)

0 Camilo
1 Santa
2 Velez


In [0]:
z=0
while z<5:
  z+=1
  print(z)

1
2
3
4
5


## Funciones

In [0]:
def mifunc(a,b,c):
  return a+b-c
print(mifunc(3,2,1))

4


In [0]:
otrafunc=lambda a,b,c: a+b-c
print(otrafunc(3,2,1))

4


## List Comprehension, Map, Filter y Reduce



In [0]:
pares=[2*x for x in range(10)]
pares

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [0]:
pares2=[2*x for x in range(10) if x%2==0]
pares2

[0, 4, 8, 12, 16]

In [0]:
cuadrados={x:x**2 for x in range(10)}
cuadrados

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [0]:
lista=range(10)
print(list(lista))
cuadrados=map(lambda x:x**2,lista)
print(cuadrados,list(cuadrados))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<map object at 0x7f89296ed908> [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [0]:
lista=range(10)
print(list(lista))
filtro=filter(lambda x: x<5,lista)
print(filtro,list(filtro))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<filter object at 0x7f89296d99e8> [0, 1, 2, 3, 4]


In [0]:
from functools import reduce
lista=range(1,10)
print(list(lista))
suma=reduce(lambda x,y: x*y,lista)
print(suma)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
362880


In [0]:
reduce?

In [0]:
sum(lista)

45

# PIP

In [0]:
!wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py --user

--2019-08-27 19:00:48--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1775417 (1.7M) [text/x-python]
Saving to: ‘get-pip.py.1’

get-pip.py.1        100%[===================>]   1.69M  --.-KB/s    in 0.09s   

2019-08-27 19:00:48 (19.7 MB/s) - ‘get-pip.py.1’ saved [1775417/1775417]

  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3


# Ambiente Virtual

In [0]:
!pip3 install --user virtualenv

In [0]:
!virtualenv nombreambiente

/bin/bash: virtualenv: command not found


In [0]:
!source nombreambiente/bin/activate

/bin/bash: nombreambiente/bin/activate: No such file or directory


In [0]:
!. nombreambiente/bin/activate

/bin/bash: nombreambiente/bin/activate: No such file or directory


In [0]:
!pip3 install --user ipykernel

In [0]:
!python3 -m ipykernel install --user --name=nombreambiente

Installed kernelspec nombreambiente in /root/.local/share/jupyter/kernels/nombreambiente


# Numpy

In [0]:
!pip3 install --user numpy

In [1]:
import numpy as np
np.__version__

'1.16.4'

In [2]:
import tensorflow as tf 
tf.__version__

'1.14.0'

In [0]:
lista1=[1,2,3,4]
arnp1=np.array(lista1)
print(lista1,type(lista1))
print(arnp1,type(arnp1))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>


In [0]:
arnp1=np.arange(0,10)
print(arnp1)
arnp1

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Filtrar

In [0]:
print(arnp1)
print(arnp1<3)
print(arnp1[arnp1%2!=0])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True False False False False False False False]
[1 3 5 7 9]


In [0]:
arr2.shape=7,3
arr2[arr2[:,-1]%2==0]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

## Indexing y Shape

In [0]:
arr1=np.arange(21)
print(arr1.shape,arr1.ndim,arr1.size,arr1.dtype)
print(arr1)

(21,) 1 21 int64
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [0]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [0]:
np.c_[arr2,np.array([0]*7).reshape((7,1)),np.arange(7)]

array([[ 0,  1,  2,  0,  0],
       [ 3,  4,  5,  0,  1],
       [ 6,  7,  8,  0,  2],
       [ 9, 10, 11,  0,  3],
       [12, 13, 14,  0,  4],
       [15, 16, 17,  0,  5],
       [18, 19, 20,  0,  6]])

In [0]:
np.r_[arr2,np.arange(3).reshape((1,3))]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [ 0,  1,  2]])

In [0]:
arr2=arr1.reshape((7,3))
print(arr2.shape,arr2.ndim,arr2.size,arr2.dtype)
print(arr2)

(7, 3) 2 21 int64
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


In [0]:
arr2.shape=3,7
print(arr2.shape,arr2.ndim,arr2.size,arr2.dtype)
print(arr2)

(3, 7) 2 21 int64
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [0]:
arr2=arr1.reshape((3,-1))
print(arr2.shape)
print(arr2)

(3, 7)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [0]:
arr2[0:2]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [0]:
arr2[0:2,1:3]

array([[1, 2],
       [8, 9]])

In [0]:
arr2.T

array([[ 0,  7, 14],
       [ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

## Zeros, Ones, Eye, Random

In [0]:
x=[1,2,3]*10
print(np.array(x),type(np.array(x)))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3] <class 'numpy.ndarray'>


In [0]:
x=np.zeros((3,9))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
y=np.ones((5,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
x.shape

(3, 9)

In [0]:
np.ones_like(x)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [0]:
np.zeros_like(x)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
np.eye?

In [0]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [0]:
np.random.uniform(3,10,(5,5))

array([[9.20036839, 6.79365836, 5.88856555, 4.26003341, 3.16743723],
       [6.45030381, 9.37478883, 5.63630619, 3.20739715, 8.48001377],
       [8.40930392, 6.72061696, 5.58905765, 3.22822617, 6.36028434],
       [7.86721383, 7.64187472, 5.24543456, 9.11430749, 6.06338731],
       [9.17030073, 3.96363148, 4.88443888, 5.27879434, 4.75273719]])

In [0]:
np.random.rand(5,5) #Ojo con argumentos

array([[0.70044685, 0.96352764, 0.08766139, 0.90447809, 0.16316506],
       [0.88847377, 0.68729812, 0.44449137, 0.32248072, 0.58998008],
       [0.94059675, 0.76365216, 0.09541182, 0.45077589, 0.27454565],
       [0.55375626, 0.0421532 , 0.41921823, 0.55380075, 0.55040509],
       [0.81784307, 0.76765327, 0.50965316, 0.12249251, 0.83319404]])

In [0]:
np.random.randn(5,5)

array([[-0.7210526 , -2.03970665, -1.23859158,  0.19634888,  0.39743677],
       [-0.34656078, -1.10143807,  0.16856816,  0.56904935,  1.09688391],
       [ 0.81570001, -0.0210451 ,  0.15006862,  1.53079874,  0.49731787],
       [-0.67965318, -1.29291069,  0.33779566,  0.37680305, -0.71949349],
       [ 1.02844327,  1.28605396,  0.65748117,  0.9137927 ,  0.19426219]])

In [0]:
np.random.normal(0,1,(5,5))

array([[-0.95651405, -0.2645284 ,  0.67770096, -0.88083764,  1.22397973],
       [-0.98718322,  1.60191849,  0.65775698, -1.46804952,  0.82509725],
       [-0.02117869,  1.14174955,  1.7518805 , -0.6007025 , -0.70972966],
       [ 2.37060613,  1.58933287,  0.78062832, -1.02245355,  0.38314517],
       [ 2.0546414 ,  1.50865961,  0.69598283, -1.24494611,  0.8911436 ]])

In [0]:
np.random.normal(0,1,(5,5))

array([[-0.6870794 ,  1.00390041, -0.66346325,  0.47068762, -1.12236686],
       [-0.48915187, -1.06017989, -0.3224292 , -0.61037848,  0.08498004],
       [-1.30254008,  1.44266215,  0.04376483, -0.07720356, -2.28107927],
       [-1.47812788,  1.30929737, -1.21905572,  0.38620258,  1.0308682 ],
       [ 1.86824419, -1.61183715,  0.39236235,  0.44394444, -0.40778212]])

## Productos

In [0]:
lista1=[1,2,3,4]
lista2=[5,6,7,8]
arnp1=np.array(lista1)
arnp2=np.arange(5,9)
print(arnp1,arnp2)
print(arnp1+arnp2)
print(arnp1*arnp2)

[1 2 3 4] [5 6 7 8]
[ 6  8 10 12]
[ 5 12 21 32]


In [0]:
lista1+lista2

[1, 2, 3, 4, 5, 6, 7, 8]

In [0]:
print(lista1*lista2)

TypeError: ignored

In [0]:
mat1=np.ones((3,5))
mat2=np.eye(5)
print(mat1.shape,mat2.shape)
z=np.dot(mat1,mat2)
z

(3, 5) (5, 5)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.dot(mat2,mat1)

ValueError: ignored

## Reduce

In [0]:
x=np.arange(12)
x=x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
print(x.sum())
print(x.mean())
print(x.std())
print(x.max())
print(x.min())

66
5.5
3.452052529534663
11
0


In [0]:
print(np.sum(x,axis=0))

[12 15 18 21]


In [0]:
print(x.sum(axis=1))

[ 6 22 38]


## Broadcasting

In [0]:
x=np.arange(12).reshape((3,4))
y=np.arange(3)
print(x)
print(y)
x*y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: ignored

In [0]:
x=np.arange(12).reshape((3,4))
y=np.arange(3).reshape((3,1))
print(x)
print(y)
x*y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0]
 [1]
 [2]]


array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [0]:
x=np.arange(24).reshape((6,4))
y=np.arange(4).reshape((1,4))
print(x)
print(y)
x*y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0 1 2 3]]


array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45],
       [ 0, 17, 36, 57],
       [ 0, 21, 44, 69]])

# Pandas

## Imports

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Dataset

In [4]:
!wget https://s3.amazonaws.com/dq-blog-files/fortune500.csv

--2019-09-03 18:52:12--  https://s3.amazonaws.com/dq-blog-files/fortune500.csv
Resolviendo s3.amazonaws.com (s3.amazonaws.com)... 52.216.169.181
Conectando con s3.amazonaws.com (s3.amazonaws.com)[52.216.169.181]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 882629 (862K) [text/csv]
Guardando como: “fortune500.csv”

fortune500.csv      100%[===================>] 861,94K   121KB/s    en 7,2s    

2019-09-03 18:52:20 (120 KB/s) - “fortune500.csv” guardado [882629/882629]



In [5]:
df = pd.read_csv('fortune500.csv')

In [6]:
len(df)

25500

In [8]:
!head fortune500.csv

In [12]:
df

Year  Rank                       Company  Revenue (in millions)  \
0      1955     1                General Motors                 9823.5   
1      1955     2                   Exxon Mobil                 5661.4   
2      1955     3                    U.S. Steel                 3250.4   
3      1955     4              General Electric                 2959.1   
4      1955     5                        Esmark                 2510.8   
5      1955     6                      Chrysler                 2071.6   
6      1955     7                        Armour                 2056.1   
7      1955     8                      Gulf Oil                 1705.3   
8      1955     9                         Mobil                 1703.6   
9      1955    10                        DuPont                 1687.7   
10     1955    11                         Amoco                 1667.4   
11     1955    12               Bethlehem Steel                 1660.3   
12     1955    13                           CBS                 1631.0   
13     1955    14                        Texaco                 1574.4   
14     1955    15             AT&T Technologies                 1526.2   
15     1955    16                     Shell Oil                 1312.1   
16     1955    17                         Kraft                 1210.3   
17     1955    18                 ChevronTexaco                 1113.3   
18     1955    19        Goodyear Tire & Rubber                 1090.1   
19     1955    20                        Boeing                 1033.2   
20     1955    21                  Sinclair Oil                 1021.5   
21     1955    22        Navistar International                  994.1   
22     1955    23                           RCA                  941.0   
23     1955    24                 Union Carbide                  923.7   
24     1955    25       Firestone Tire & Rubber                  916.0   
25     1955    26              Douglas Aircraft                  915.2   
26     1955    27              Procter & Gamble                  911.0   
27     1955    28                Republic Steel                  846.3   
28     1955    29               Citgo Petroleum                  813.2   
29     1955    30                ConocoPhillips                  794.6   
...     ...   ...                           ...                    ...   
25470  2005   471              Wisconsin Energy                 3912.1   
25471  2005   472       American Financial Grp.                 3911.7   
25472  2005   473              Beazer Homes USA                 3907.1   
25473  2005   474              Collins & Aikman                 3904.0   
25474  2005   475                 Borders Group                 3903.0   
25475  2005   476                    Nash Finch                 3897.1   
25476  2005   477                 Toll Brothers                 3893.1   
25477  2005   478                         SCANA                 3885.0   
25478  2005   479            Whole Foods Market                 3864.9   
25479  2005   480                       Corning                 3854.0   
25480  2005   481                    Sealed Air                 3798.1   
25481  2005   482                        Maxtor                 3796.3   
25482  2005   483          Reebok International                 3785.3   
25483  2005   484                           UGI                 3784.7   
25484  2005   485                       Guidant                 3775.2   
25485  2005   486                 Host Marriott                 3773.0   
25486  2005   487            Advance Auto Parts                 3770.3   
25487  2005   488                 ServiceMaster                 3759.6   
25488  2005   489           Wesco International                 3741.3   
25489  2005   490         Telephone & Data Sys.                 3720.4   
25490  2005   491        Level 3 Communications                 3712.0   
25491  2005   492         Brinker International                 3707.5   
25492  2005

In [0]:
df.dtypes

Year                       int64
Rank                       int64
Company                   object
Revenue (in millions)    float64
Profit (in millions)      object
dtype: object

In [0]:
df.columns = ['Año', 'Rango', 'Compañía', 'Ingresos', 'Ganancias']

In [0]:
df.describe()

Año         Rango       Ingresos
count  25500.00000  25500.000000   25500.000000
mean    1980.00000    250.499765    4273.329635
std       14.71989    144.339963   11351.884979
min     1955.00000      1.000000      49.700000
25%     1967.00000    125.750000     362.300000
50%     1980.00000    250.500000    1019.000000
75%     1993.00000    375.250000    3871.000000
max     2005.00000    500.000000  288189.000000

In [0]:
df.mean() #min, max, std

Año          1980.004903
Rango         250.509432
Ingresos     4273.381176
Ganancias     204.894886
dtype: float64

In [0]:
df['Compañía'].value_counts().head()

CBS               57
OfficeMax         55
Crown Holdings    51
Whirlpool         51
General Mills     51
Name: Compañía, dtype: int64

In [0]:
df.head()

Año  Rango          Compañía  Ingresos Ganancias
0  1955      1    General Motors    9823.5       806
1  1955      2       Exxon Mobil    5661.4     584.8
2  1955      3        U.S. Steel    3250.4     195.4
3  1955      4  General Electric    2959.1     212.6
4  1955      5            Esmark    2510.8      19.1

In [0]:
df.tail()

Año  Rango               Compañía  Ingresos Ganancias
25495  2005    496        Wm. Wrigley Jr.    3648.6       493
25496  2005    497         Peabody Energy    3631.6     175.4
25497  2005    498  Wendy's International    3630.4      57.8
25498  2005    499     Kindred Healthcare    3616.6      70.6
25499  2005    500   Cincinnati Financial    3614.0       584

## Seleccionar

In [0]:
df.Año

0        1955
1        1955
2        1955
3        1955
4        1955
5        1955
6        1955
7        1955
8        1955
9        1955
10       1955
11       1955
12       1955
13       1955
14       1955
15       1955
16       1955
17       1955
18       1955
19       1955
20       1955
21       1955
22       1955
23       1955
24       1955
25       1955
26       1955
27       1955
28       1955
29       1955
         ... 
25470    2005
25471    2005
25472    2005
25473    2005
25474    2005
25475    2005
25476    2005
25477    2005
25478    2005
25479    2005
25480    2005
25481    2005
25482    2005
25483    2005
25484    2005
25485    2005
25486    2005
25487    2005
25488    2005
25489    2005
25490    2005
25491    2005
25492    2005
25493    2005
25494    2005
25495    2005
25496    2005
25497    2005
25498    2005
25499    2005
Name: Año, Length: 25500, dtype: int64

In [0]:
df['Año']

0        1955
1        1955
2        1955
3        1955
4        1955
5        1955
6        1955
7        1955
8        1955
9        1955
10       1955
11       1955
12       1955
13       1955
14       1955
15       1955
16       1955
17       1955
18       1955
19       1955
20       1955
21       1955
22       1955
23       1955
24       1955
25       1955
26       1955
27       1955
28       1955
29       1955
         ... 
25470    2005
25471    2005
25472    2005
25473    2005
25474    2005
25475    2005
25476    2005
25477    2005
25478    2005
25479    2005
25480    2005
25481    2005
25482    2005
25483    2005
25484    2005
25485    2005
25486    2005
25487    2005
25488    2005
25489    2005
25490    2005
25491    2005
25492    2005
25493    2005
25494    2005
25495    2005
25496    2005
25497    2005
25498    2005
25499    2005
Name: Año, Length: 25500, dtype: int64

In [0]:
type(df['Año'])

pandas.core.series.Series

In [0]:
df[0:5]

Año  Rango          Compañía  Ingresos  Ganancias
0  1955      1    General Motors    9823.5      806.0
1  1955      2       Exxon Mobil    5661.4      584.8
2  1955      3        U.S. Steel    3250.4      195.4
3  1955      4  General Electric    2959.1      212.6
4  1955      5            Esmark    2510.8       19.1

In [0]:
df.iloc[0:5]

Año  Rango          Compañía  Ingresos  Ganancias
0  1955      1    General Motors    9823.5      806.0
1  1955      2       Exxon Mobil    5661.4      584.8
2  1955      3        U.S. Steel    3250.4      195.4
3  1955      4  General Electric    2959.1      212.6
4  1955      5            Esmark    2510.8       19.1

In [0]:
df.iloc[0:5,[2,4]]

Compañía  Ganancias
0    General Motors      806.0
1       Exxon Mobil      584.8
2        U.S. Steel      195.4
3  General Electric      212.6
4            Esmark       19.1

In [0]:
df.loc[0:5] #Ojo con el 5

Año  Rango          Compañía  Ingresos  Ganancias
0  1955      1    General Motors    9823.5      806.0
1  1955      2       Exxon Mobil    5661.4      584.8
2  1955      3        U.S. Steel    3250.4      195.4
3  1955      4  General Electric    2959.1      212.6
4  1955      5            Esmark    2510.8       19.1
5  1955      6          Chrysler    2071.6       18.5

In [0]:
df.loc[0:5,['Compañía','Ganancias']]

Compañía  Ganancias
0    General Motors      806.0
1       Exxon Mobil      584.8
2        U.S. Steel      195.4
3  General Electric      212.6
4            Esmark       19.1
5          Chrysler       18.5

## Arreglar no-numéricos

In [0]:
df['Ganancias']=pd.to_numeric(df['Ganancias'],errors='coerce')
df.dtypes

Año            int64
Rango          int64
Compañía      object
Ingresos     float64
Ganancias    float64
dtype: object

In [0]:
ganan=df.Ganancias.isna()
df[ganan]

Año  Rango                          Compañía  Ingresos  Ganancias
228    1955    229                            Norton     135.0        NaN
290    1955    291                   Schlitz Brewing     100.0        NaN
294    1955    295             Pacific Vegetable Oil      97.9        NaN
296    1955    297                Liebmann Breweries      96.0        NaN
352    1955    353                Minneapolis-Moline      77.4        NaN
464    1955    465                   Gilfillan Bros.      54.0        NaN
712    1956    213                            Norton     160.5        NaN
857    1956    358                Liebmann Breweries      83.0        NaN
1225   1957    226                            Norton     173.0        NaN
1372   1957    373                Liebmann Breweries      90.0        NaN
1419   1957    420        Crowell-Collier Publishing      74.8        NaN
1717   1958    218  Hearst Consolidated Publications     195.7        NaN
1738   1958    239                            Norton     176.8        NaN
1900   1958    401                Liebmann Breweries      85.0        NaN
2264   1959    265                            Norton     150.0        NaN
2456   1959    457                        Joy Global      68.9        NaN
2491   1959    492                  Suntide Refining      63.0        NaN
2754   1960    255                            Norton     174.9        NaN
3253   1961    254                            Norton     181.9        NaN
3442   1961    443                     Alco Products      86.7        NaN
3754   1962    255                            Norton     178.8        NaN
3998   1962    499                     Fuller (W.P.)      76.2        NaN
5485   1965    486                          Seaboard     101.5        NaN
8032   1971     33                   Lockheed Martin    2535.0        NaN
8183   1971    184                      Land O'Lakes     654.3        NaN
8191   1971    192               Farmland Industries     612.8        NaN
8193   1971    194                             Agway     597.9        NaN
8296   1971    297                Gold Kist Holdings     347.9        NaN
8313   1971    314              Dairylea Cooperative     327.3        NaN
8481   1971    482    Farmers Union Central Exchange     175.3        NaN
...     ...    ...                               ...       ...        ...
20989  1996    490                          Roundy's    2488.2        NaN
20996  1996    497                        True Value    2437.0        NaN
20997  1996    498                      Ace Hardware    2436.0        NaN
21085  1997     86  College Retirement Equities Fund   13864.6        NaN
21150  1997    151               Farmland Industries    9788.6        NaN
21477  1997    478                      Ace Hardware    2742.5        NaN
21497  1997    498                          Roundy's    2583.5        NaN
21669  1998    170               Farmland Industries    9147.5        NaN
21931  1998    432                        True Value    3332.0        NaN
21981  1998    482                      Ace Hardware    2907.3        NaN
22183  1999    184               Farmland Industries    8775.0        NaN
22359  1999    360                        True Value    4328.2        NaN
22466  1999    467                      Ace Hardware    3120.4        NaN
22660  2000    161               Farmland Industries   10709.1        NaN
22766  2000    267                               CHS    6434.5        NaN
22856  2000    357                        True Value    4502.3        NaN
22981  2000    482                      Ace Hardware    3181.8        NaN
23159  2001    160               Farmland Industries   12239.0        NaN
23222  2001    223                               CHS    8571.4        NaN
23402  2001    403                        True Value    4159.0        NaN
23504  2002      5                             Enron  138718.0        NaN
23669  2002    170               Farmland Industries   11763.4        NaN
23743  2002 

In [0]:
df.loc[ganan,'Ganancias']=0

In [0]:
df[ganan]

Año  Rango                          Compañía  Ingresos  Ganancias
228    1955    229                            Norton     135.0        0.0
290    1955    291                   Schlitz Brewing     100.0        0.0
294    1955    295             Pacific Vegetable Oil      97.9        0.0
296    1955    297                Liebmann Breweries      96.0        0.0
352    1955    353                Minneapolis-Moline      77.4        0.0
464    1955    465                   Gilfillan Bros.      54.0        0.0
712    1956    213                            Norton     160.5        0.0
857    1956    358                Liebmann Breweries      83.0        0.0
1225   1957    226                            Norton     173.0        0.0
1372   1957    373                Liebmann Breweries      90.0        0.0
1419   1957    420        Crowell-Collier Publishing      74.8        0.0
1717   1958    218  Hearst Consolidated Publications     195.7        0.0
1738   1958    239                            Norton     176.8        0.0
1900   1958    401                Liebmann Breweries      85.0        0.0
2264   1959    265                            Norton     150.0        0.0
2456   1959    457                        Joy Global      68.9        0.0
2491   1959    492                  Suntide Refining      63.0        0.0
2754   1960    255                            Norton     174.9        0.0
3253   1961    254                            Norton     181.9        0.0
3442   1961    443                     Alco Products      86.7        0.0
3754   1962    255                            Norton     178.8        0.0
3998   1962    499                     Fuller (W.P.)      76.2        0.0
5485   1965    486                          Seaboard     101.5        0.0
8032   1971     33                   Lockheed Martin    2535.0        0.0
8183   1971    184                      Land O'Lakes     654.3        0.0
8191   1971    192               Farmland Industries     612.8        0.0
8193   1971    194                             Agway     597.9        0.0
8296   1971    297                Gold Kist Holdings     347.9        0.0
8313   1971    314              Dairylea Cooperative     327.3        0.0
8481   1971    482    Farmers Union Central Exchange     175.3        0.0
...     ...    ...                               ...       ...        ...
20989  1996    490                          Roundy's    2488.2        0.0
20996  1996    497                        True Value    2437.0        0.0
20997  1996    498                      Ace Hardware    2436.0        0.0
21085  1997     86  College Retirement Equities Fund   13864.6        0.0
21150  1997    151               Farmland Industries    9788.6        0.0
21477  1997    478                      Ace Hardware    2742.5        0.0
21497  1997    498                          Roundy's    2583.5        0.0
21669  1998    170               Farmland Industries    9147.5        0.0
21931  1998    432                        True Value    3332.0        0.0
21981  1998    482                      Ace Hardware    2907.3        0.0
22183  1999    184               Farmland Industries    8775.0        0.0
22359  1999    360                        True Value    4328.2        0.0
22466  1999    467                      Ace Hardware    3120.4        0.0
22660  2000    161               Farmland Industries   10709.1        0.0
22766  2000    267                               CHS    6434.5        0.0
22856  2000    357                        True Value    4502.3        0.0
22981  2000    482                      Ace Hardware    3181.8        0.0
23159  2001    160               Farmland Industries   12239.0        0.0
23222  2001    223                               CHS    8571.4        0.0
23402  2001    403                        True Value    4159.0        0.0
23504  2002      5                             Enron  138718.0        0.0
23669  2002    170               Farmland Industries   11763.4        0.0
23743  2002 

## Datos Faltantes

In [0]:
df.iloc[0:5,0]=np.nan
df.iloc[3]=np.nan

In [0]:
df.iloc[0:5]

Año  Rango        Compañía  Ingresos  Ganancias
0  NaN    1.0  General Motors    9823.5      806.0
1  NaN    2.0     Exxon Mobil    5661.4      584.8
2  NaN    3.0      U.S. Steel    3250.4      195.4
3  NaN    NaN             NaN       NaN        NaN
4  NaN    5.0          Esmark    2510.8       19.1

In [0]:
df.fillna(5).head()

Año  Rango        Compañía  Ingresos  Ganancias
0  5.0    1.0  General Motors    9823.5      806.0
1  5.0    2.0     Exxon Mobil    5661.4      584.8
2  5.0    3.0      U.S. Steel    3250.4      195.4
3  5.0    5.0               5       5.0        5.0
4  5.0    5.0          Esmark    2510.8       19.1

In [0]:
df.dropna(how='all').head()

Año  Rango        Compañía  Ingresos  Ganancias
0     NaN    1.0  General Motors    9823.5      806.0
1     NaN    2.0     Exxon Mobil    5661.4      584.8
2     NaN    3.0      U.S. Steel    3250.4      195.4
4     NaN    5.0          Esmark    2510.8       19.1
5  1955.0    6.0        Chrysler    2071.6       18.5

In [0]:
df.dropna(how='any').head()

Año  Rango  Compañía  Ingresos  Ganancias
5  1955.0    6.0  Chrysler    2071.6       18.5
6  1955.0    7.0    Armour    2056.1        1.6
7  1955.0    8.0  Gulf Oil    1705.3      182.8
8  1955.0    9.0     Mobil    1703.6      183.8
9  1955.0   10.0    DuPont    1687.7      344.4

## Texto

In [0]:
df['Compañía'].head()

0    General Motors
1       Exxon Mobil
2        U.S. Steel
3               NaN
4            Esmark
Name: Compañía, dtype: object

In [0]:
df['Compañía'].str.lower().head()

0    general motors
1       exxon mobil
2        u.s. steel
3               NaN
4            esmark
Name: Compañía, dtype: object