<img src="https://cdn-images-1.medium.com/max/400/1*mc5YIn7jvo5uwuqBOUDw7Q.jpeg"/>

In [80]:
import numpy as np #importamos la libreria numpy

# Dims

In [2]:
x=np.array(1)
print('Forma: ', x.shape)
print('Dim: ', x.ndim)
print('x:')
x

Forma:  ()
Dim:  0
x:


array(1)

In [3]:
x=np.array([1,2,3]) #construyo una lista con np.array
print('Forma: ', x.shape) #np.shape me arroja el tamaño de mi matriz
print('Dim: ', x.ndim)
print('x:')
x

Forma:  (3,)
Dim:  1
x:


array([1, 2, 3])

In [9]:
x=np.array([[1,2,3],[4,5,6]]) #contruyo una matriz de 2 filas por 3 columnas
print('Forma: ', x.shape)
print('Dim: ', x.ndim)
print('x:')
x

Forma:  (2, 3)
Dim:  2
x:


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,2,3]]]) #construyo un tensor que tiene dos matriz y cada matriz de 2 
#filas por 3 columnas
print('Forma: ', x.shape) #con x.shape imprimo el tamaño de mi matriz
print('Dim: ', x.ndim)
print('x:')
x

Forma:  (2, 2, 3)
Dim:  3
x:


array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 3]]])

In [4]:
x=np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
j=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
<class 'numpy.ndarray'>


# Rangos

In [12]:
print(np.arange(10)) #con np.arange() puedo imprimir un vector con numeros del 0 al 9
print(np.arange(3,10)) #imprime un vector con numeros del 3 al 9
print(np.arange(3,10,0.5))#imprime un vector del 3 al 9 con saltos de 0.5

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [18]:
j=np.arange(20) #imprime un vector de 20 valores
print(j)
print(j.shape)
print(j.ndim)
print(type(j))
j=np.arange(2,20) #imprime los valores del 2 al 20 de uno en uno
print(j)
print(j.shape)
print(j.ndim)
print(type(j))
j=np.arange(2,12,3) #imprime los valores del 2 al 12 con saltos de 3
print(j)
print(j.shape)
print(j.ndim)
print(type(j))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
1
<class 'numpy.ndarray'>
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(18,)
1
<class 'numpy.ndarray'>
[ 2  5  8 11]
(4,)
1
<class 'numpy.ndarray'>


In [10]:
print(np.linspace(0,10,21)) #con el comando np.linspace imprimo entre 0 y 10 21 valores
#que estan espacios igualmente

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [20]:
j=np.linspace(0,20,3) #np.linspace imprime numeros igualmente espaciados en el intervalo dado
print(j)
print(j.shape)
print(j.ndim)
print(type(j))


[ 0. 10. 20.]
(3,)
1
<class 'numpy.ndarray'>


# Zeros, Ones, Rand

In [11]:
z=np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
j=np.zeros((3,3)) #np.zeros para imprimir matriz de ceros de orden 3*3
print(j)
print(j)
print(j.shape)
print(j.ndim)
print(type(j))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
2
<class 'numpy.ndarray'>


In [12]:
o=np.ones((5,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
j=np.ones((3,3)) #imprime matriz de unos de orden 3*3
print(j)
print(j.shape)
print(j.ndim)
print(type(j))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
2
<class 'numpy.ndarray'>


In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
j=np.eye(4) #imprime matriz cuadrada pero diagonal con uno
print(j)
print(j.shape)
print(j.ndim)
print(type(j))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
2
<class 'numpy.ndarray'>


In [243]:
x

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 2, 3]]])

In [ ]:
j=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

In [244]:
z=np.zeros_like(x)
z

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [28]:
a=np.zeros_like(j)# convierte los elementos de la matriz j a cero pero conserva el mismo tamaño
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
a=np.ones_like(j)# convierte los elementos de la matriz j a uno pero conserva el mismo tamaño
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [245]:
o=np.ones_like(x)
o

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

## Uniforme

In [14]:
u=5*np.random.random((5,4))+3
u

array([[5.23397787, 5.60924231, 7.43392177, 6.03244589],
       [6.70730446, 4.79846713, 5.98831933, 5.39907535],
       [4.36968395, 4.6594974 , 6.13121781, 6.05763987],
       [7.08459226, 5.30442367, 7.74167192, 5.11836989],
       [4.57190253, 6.21639973, 4.12728053, 6.75393612]])

In [36]:
j=np.random.random((3,3)) # imprime matriz de orden 3 pero con valores aleatorios entre 0 y 1 
#(los valores son una distribucion uniforme entre 0 y 1)
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))
j=5*np.random.random((3,3)) # imprime matriz de orden 3 pero con valores aleatorios entre 0 y 5 
#(los valores son una distribucion uniforme entre 0 y 5)
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))
j=5*np.random.random((3,3)) + 3 # imprime matriz de orden 3 pero con valores aleatorios entre 3 y 8
#(los valores son una distribucion uniforme desplazada del origen)
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

[[0.9761142  0.35141977 0.99557131]
 [0.01962731 0.91398009 0.69374291]
 [0.99950369 0.22264555 0.76528873]]
(3, 3)
2
<class 'numpy.ndarray'>
[[3.90658673 4.0717188  3.62995752]
 [4.87849618 3.03746813 2.67163292]
 [4.42504849 3.20794845 3.95801302]]
(3, 3)
2
<class 'numpy.ndarray'>
[[3.02780909 4.94978045 3.21089543]
 [7.96608445 4.65717428 7.26162095]
 [5.87206203 4.55587491 7.16797953]]
(3, 3)
2
<class 'numpy.ndarray'>


In [250]:
ui=np.random.randint(0,10,(5,4)) #Ojo con los parametros
ui

array([[8, 3, 6, 8],
       [3, 6, 5, 0],
       [0, 8, 6, 6],
       [8, 1, 8, 7],
       [2, 9, 2, 6]])

In [48]:
j=np.random.randint(2,7,(3,3)) # imprime matriz de orden 3 pero con valores aleatorios enteros entre 2 y 6
#(los valores son una distribucion uniforme)
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

[[3 3 3]
 [3 5 6]
 [6 5 4]]
(3, 3)
2
<class 'numpy.ndarray'>


## Normal

In [17]:
r=np.random.randn(7,3) #Ojo con las dims
r

array([[ 1.92077525,  1.17994723, -0.43732273],
       [-0.9990928 , -0.86437806, -0.99389476],
       [-0.25710805, -1.32841485, -0.01910726],
       [ 1.12812713,  1.77373887,  0.75393689],
       [ 1.70848521,  1.60271141,  0.57167661],
       [-0.23221359,  2.02522125,  0.53759781],
       [-0.44997331, -1.66858607,  1.00826231]])

In [54]:
j=np.random.randn(4,4)# imprime matriz de orden 3 pero con valores aleatorios entre -2 y 2
#(los valores son una distribucion normal)
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

[[-1.4039448  -0.07215936 -2.2084462   0.24580093]
 [ 1.74532848  2.72316159  0.77342099  0.93213277]
 [-0.45779822  1.50388163  0.94387487  0.06984927]
 [ 0.79299127  0.35588562 -2.04378414 -0.43781414]]
(4, 4)
2
<class 'numpy.ndarray'>


# Indices ¡¡¡MUY IMPORTANTE

In [71]:
a=np.random.random((10,10)) #matriz de numeros aleatorios entre 0 y 1 con matriz de orden 10
a

array([[0.37636837, 0.24971757, 0.13046677, 0.22653427, 0.02508565,
        0.33022934, 0.24662586, 0.7757695 , 0.81169922, 0.46423294],
       [0.23968422, 0.05457296, 0.47996482, 0.06055449, 0.9295508 ,
        0.927754  , 0.59924041, 0.71651826, 0.11390867, 0.75857736],
       [0.78943754, 0.78422992, 0.31144496, 0.43699425, 0.1423068 ,
        0.42012252, 0.68253577, 0.87921588, 0.68461363, 0.81436407],
       [0.99959924, 0.63153515, 0.60370101, 0.92599013, 0.09402469,
        0.26559907, 0.90880189, 0.39712907, 0.47484159, 0.06075502],
       [0.55849617, 0.64176974, 0.40783762, 0.1195226 , 0.40327829,
        0.84628381, 0.93408867, 0.78511933, 0.11868864, 0.51907248],
       [0.85840533, 0.98912262, 0.62793875, 0.78039571, 0.80988713,
        0.59944534, 0.07797227, 0.91129829, 0.80046259, 0.01651328],
       [0.44952324, 0.34407766, 0.78401706, 0.45976802, 0.12624333,
        0.3135776 , 0.64299882, 0.54659783, 0.01180132, 0.98115824],
       [0.52435668, 0.60637786, 0.5448402

In [56]:
j=np.random.random((5,5))
print(j)
print(j.shape)
print(j.ndim) #tipo de dimension de tensor
print(type(j))

[[0.75670431 0.55040448 0.86266579 0.50824516 0.9966984 ]
 [0.05649126 0.11393686 0.51359198 0.8000438  0.60817022]
 [0.46777972 0.76480821 0.68730096 0.34694    0.33331129]
 [0.77256866 0.34898472 0.29832493 0.93391593 0.08967059]
 [0.49662702 0.21401509 0.45235541 0.07315452 0.78953828]]
(5, 5)
2
<class 'numpy.ndarray'>


In [87]:
ind=j[:,:] #MUY IMPORTANTE
#print(ind)
ind=j[0:4,:] #imprime desde la fila 0 hasta la 3 y todos los de la columna
#print(ind)
ind=j[0:4,0:4] #imprime desde la fila 0 hasta la 3 y desde la columna 0 hasta la columna 3
#print(ind)
ind=j[0:4:2,0:4] #imprime desde la fila 0 hasta la 3 con saltos de 2 y desde la columna 0 hasta la columna 3
#print(ind)
ind=j[0:4:2,0:4:3] #imprime desde la fila 0 hasta la 3 con saltos de 2 y desde la columna 0 hasta la columna 3 
#con saltos de 3
#print(ind)
ind=j[:,:-1] #imprime toda la matriz sin contar la ultima columna
#print(ind)
ind=j[:,-1] #imprime la ultima columna pero en forma de fila
#print(ind)
#print(ind.shape)
#x=ind.reshape(5,1)#reorganizamos
#print(x)
#print(x.shape)
ind=j[[1,2,3],:] #imprime solo las filas 1,2 y 3 pero con todas las columnas
#print(ind)
ind=j[:,[1,2,3]] #imprime todas las filas pero solo las columnas 1,2 y 3
print(ind)

[[0.55040448 0.86266579 0.50824516]
 [0.11393686 0.51359198 0.8000438 ]
 [0.76480821 0.68730096 0.34694   ]
 [0.34898472 0.29832493 0.93391593]
 [0.21401509 0.45235541 0.07315452]]


In [72]:
print(a[0:5:2,3:7:2])

[[0.22653427 0.33022934]
 [0.43699425 0.42012252]
 [0.1195226  0.84628381]]


In [73]:
print(a[1,:])

[0.23968422 0.05457296 0.47996482 0.06055449 0.9295508  0.927754
 0.59924041 0.71651826 0.11390867 0.75857736]


In [82]:
print(a[:,1])

[0.24971757 0.05457296 0.78422992 0.63153515 0.64176974 0.98912262
 0.34407766 0.60637786 0.22150498 0.33580393]


In [83]:
print(a[[1,3],:])

[[0.23968422 0.05457296 0.47996482 0.06055449 0.9295508  0.927754
  0.59924041 0.71651826 0.11390867 0.75857736]
 [0.99959924 0.63153515 0.60370101 0.92599013 0.09402469 0.26559907
  0.90880189 0.39712907 0.47484159 0.06075502]]


In [268]:
print(a[:,[0,2]])

[[ 0.92512857  0.0121937 ]
 [ 0.0187526   0.13405869]
 [ 0.14089764  0.60304198]
 [ 0.33263295  0.52915523]
 [ 0.34195761  0.76590132]
 [ 0.0231134   0.16913683]
 [ 0.44583081  0.93127076]
 [ 0.47239639  0.96045364]
 [ 0.46107096  0.89942057]
 [ 0.15251982  0.56093715]]


# Reshape

In [88]:
x=np.arange(0,12) #el comando reshape es muy importante y sirve para reorganizar la matriz
print(x.shape) #preguntar al profesor
print(x.ndim)
x

(12,)
1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
x=x.reshape((3,4))
print(x.shape)
print(x.ndim)
x

(3, 4)
2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
x=x.reshape((2,3,2)) #se puede reorganizar en un tensor de rango 3 siempre y cuando no pierda el orden
print(x.shape)
print(x.ndim)
x

(2, 3, 2)
3


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [93]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Transpose

In [94]:
x=np.arange(6).reshape((2,3))
print(x.shape)
print(x.ndim)
x

(2, 3)
2


array([[0, 1, 2],
       [3, 4, 5]])

In [95]:
x=x.T #transpuesta de una matriz
print(x.shape)
print(x.ndim)
x

(3, 2)
2


array([[0, 3],
       [1, 4],
       [2, 5]])

No es un reshape!

# Broadcasting

In [96]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(x.ndim)
x

(2, 3)
2


array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
y=np.array([1,2,3])
print(y.shape)
print(y.ndim)
y

(3,)
1


array([1, 2, 3])

In [98]:
x+y #como x es 2*3 y y es 1*3 entonces se completa y para ser 2*3 con los mismos valores que tiene

array([[2, 4, 6],
       [5, 7, 9]])

In [99]:
x+y+1

array([[ 3,  5,  7],
       [ 6,  8, 10]])

<img src="http://tripkendall.com/wp-content/uploads/2018/01/pandas_logo-1080x675.jpg"/>

In [27]:
import pandas as pd

In [28]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
print(data)
print(type(data))

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.series.Series'>


In [29]:
#construyamos una base de datos

In [30]:
basedata=pd.Series([13.4,5,True,"hello",34], index=["julian","andres","montoya","carvajal","mundo"])
print(basedata)

julian       13.4
andres          5
montoya      True
carvajal    hello
mundo          34
dtype: object


In [31]:
print(basedata.values) #imprime columna de valores

[13.4 5 True 'hello' 34]


In [32]:
print(basedata.index) #imprime columna de indices

Index(['julian', 'andres', 'montoya', 'carvajal', 'mundo'], dtype='object')


In [33]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [34]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [35]:
print(data.loc['a'])
print(data.iloc[0])

0.25
0.25


In [36]:
dictAltura =  {'Camilo': 180, 
               'Edison': 164, 
               'Oscar': 175,
               'Daniel': 165, 
               'Patricia': 160}
dictPeso =  {'Camilo': 80, 
               'Edison': 64, 
               'Oscar': 75,
               'Daniel': 65, 
               'Patricia': 60}

In [37]:
#construir un dataframe


In [38]:
notamaterias= {"inteligencia artificial": 4.5,
              "ingles 1": 4.0,
              "probabilidad": 3.5,
               "fisica computacional": 4
              }

In [39]:
profesormate={"inteligencia artificial": "Edison",
              "ingles 1": "nn",
              "probabilidad": "juan jose",
               "fisica computacional": "jose david"
              }

In [40]:
notas=pd.Series(notamaterias)
profesores=pd.Series(profesormate)
print(notas)
print(profesores)

inteligencia artificial    4.5
ingles 1                   4.0
probabilidad               3.5
fisica computacional       4.0
dtype: float64
inteligencia artificial        Edison
ingles 1                           nn
probabilidad                juan jose
fisica computacional       jose david
dtype: object


In [41]:
tabla=pd.DataFrame({"notas":notas,"profesores":profesores}) #construimos dataframe
print(tabla)

                         notas  profesores
inteligencia artificial    4.5      Edison
ingles 1                   4.0          nn
probabilidad               3.5   juan jose
fisica computacional       4.0  jose david


In [42]:
tabla.describe() #da una descripcion del dataframe

notas
count  4.000000
mean   4.000000
std    0.408248
min    3.500000
25%    3.875000
50%    4.000000
75%    4.125000
max    4.500000

In [43]:
tabla.min()

notas            3.5
profesores    Edison
dtype: object

In [44]:
alts=pd.Series(dictAltura)
alts

Camilo      180
Edison      164
Oscar       175
Daniel      165
Patricia    160
dtype: int64

In [45]:
pesos=pd.Series(dictPeso)
pesos

Camilo      80
Edison      64
Oscar       75
Daniel      65
Patricia    60
dtype: int64

In [46]:
gente=pd.DataFrame({'Altura':alts,'Peso':pesos})
gente

Altura  Peso
Camilo       180    80
Edison       164    64
Oscar        175    75
Daniel       165    65
Patricia     160    60

In [47]:
gente.describe()

Altura       Peso
count    5.000000   5.000000
mean   168.800000  68.800000
std      8.348653   8.348653
min    160.000000  60.000000
25%    164.000000  64.000000
50%    165.000000  65.000000
75%    175.000000  75.000000
max    180.000000  80.000000

In [48]:
gente.min()

Altura    160
Peso       60
dtype: int64

In [65]:
tabla=pd.DataFrame({"notas":notas,"profesores":profesores}) #construimos dataframe
print(tabla)

                         notas  profesores
inteligencia artificial    4.5      Edison
ingles 1                   4.0          nn
probabilidad               3.5   juan jose
fisica computacional       4.0  jose david


## Agregar Filas & Columnas

In [66]:
tabla["dificultad"]=["difcil", "facil", "medio", "dificil"] #agregamos una columna llamada dificultad
tabla

notas  profesores dificultad
inteligencia artificial    4.5      Edison     difcil
ingles 1                   4.0          nn      facil
probabilidad               3.5   juan jose      medio
fisica computacional       4.0  jose david    dificil

In [67]:
tabla.loc["fotonica"]=[0.0,"Rodrigo","ninguna"] #con .loc agregamos una fila llamada fotonica
tabla

notas  profesores dificultad
inteligencia artificial    4.5      Edison     difcil
ingles 1                   4.0          nn      facil
probabilidad               3.5   juan jose      medio
fisica computacional       4.0  jose david    dificil
fotonica                   0.0     Rodrigo    ninguna

In [68]:
tabla.drop("profesores",1,inplace=True) #con .drop borramos la columna escrita
tabla

notas dificultad
inteligencia artificial    4.5     difcil
ingles 1                   4.0      facil
probabilidad               3.5      medio
fisica computacional       4.0    dificil
fotonica                   0.0    ninguna

In [70]:
tabla.drop("fotonica") #borramos una fila

notas dificultad
inteligencia artificial    4.5     difcil
ingles 1                   4.0      facil
probabilidad               3.5      medio
fisica computacional       4.0    dificil

In [51]:
gente['Edad']=[5,4,3,2,1]
gente

Altura  Peso  Edad
Camilo       180    80     5
Edison       164    64     4
Oscar        175    75     3
Daniel       165    65     2
Patricia     160    60     1

In [56]:
gente.loc['Boris']=[190,85,0]
gente

Altura  Peso  Edad
Camilo       180    80     5
Edison       164    64     4
Oscar        175    75     3
Daniel       165    65     2
Patricia     160    60     1
Boris        190    85     0

In [57]:
gente['Key']=[1,0,1,0,1,0]
gente

Altura  Peso  Edad  Key
Camilo       180    80     5    1
Edison       164    64     4    0
Oscar        175    75     3    1
Daniel       165    65     2    0
Patricia     160    60     1    1
Boris        190    85     0    0

In [58]:
gente.drop('Key',1,inplace=True)
gente

Altura  Peso  Edad
Camilo       180    80     5
Edison       164    64     4
Oscar        175    75     3
Daniel       165    65     2
Patricia     160    60     1
Boris        190    85     0

In [59]:
gente.loc['Federico']=[190,85,0]
gente

Altura  Peso  Edad
Camilo       180    80     5
Edison       164    64     4
Oscar        175    75     3
Daniel       165    65     2
Patricia     160    60     1
Boris        190    85     0
Federico     190    85     0

In [60]:
gente=gente.drop('Federico')
gente

Altura  Peso  Edad
Camilo       180    80     5
Edison       164    64     4
Oscar        175    75     3
Daniel       165    65     2
Patricia     160    60     1
Boris        190    85     0

## Agrupar

In [71]:
gente['Ciudad']=['Medellin','Bogota','Medellin','Medellin','Cali','Cali']
gente

Altura  Peso  Edad    Ciudad
Camilo       180    80     5  Medellin
Edison       164    64     4    Bogota
Oscar        175    75     3  Medellin
Daniel       165    65     2  Medellin
Patricia     160    60     1      Cali
Boris        190    85     0      Cali

In [72]:
gente.groupby('Ciudad').sum() #agrupamls y sumamos

Altura  Peso  Edad
Ciudad                      
Bogota       164    64     4
Cali         350   145     1
Medellin     520   220    10

## Indices

In [73]:
gente.index #me saca la columna de etiquetas

Index(['Camilo', 'Edison', 'Oscar', 'Daniel', 'Patricia', 'Boris'], dtype='object')

In [74]:
gente.Altura #me saca solo la columna de altura

Camilo      180
Edison      164
Oscar       175
Daniel      165
Patricia    160
Boris       190
Name: Altura, dtype: int64

In [75]:
print(gente['Altura']) #me saca solo la columna de altura

Camilo      180
Edison      164
Oscar       175
Daniel      165
Patricia    160
Boris       190
Name: Altura, dtype: int64


In [76]:
gente.loc['Camilo'] #selecciona sola esta fila con cada una de las columnas

Altura         180
Peso            80
Edad             5
Ciudad    Medellin
Name: Camilo, dtype: object

In [77]:
gente.loc['Camilo','Peso'] #me saca el dato de la fila y la columna indicada

80

In [78]:
gente.iloc[1,1] #¿?

64

## Data Cleaning o limpieza de datos

In [87]:
datos = pd.DataFrame({'Edad': [0, 1, np.nan,np.nan],'Altura':[1,2,3,np.nan],'Peso':[np.nan,2,np.nan,np.nan]},index=['Camilo', 'Edison', 'Oscar','Patricia'])
datos

Edad  Altura  Peso
Camilo     0.0     1.0   NaN
Edison     1.0     2.0   2.0
Oscar      NaN     3.0   NaN
Patricia   NaN     NaN   NaN

In [88]:
datos.isnull() #los datos con valor NaN se ponen como True

Edad  Altura   Peso
Camilo    False   False   True
Edison    False   False  False
Oscar      True   False   True
Patricia   True    True   True

In [89]:
datos.dropna() #saca la fila que no tiene datos nulos

Edad  Altura  Peso
Edison   1.0     2.0   2.0

In [95]:
datos.dropna(thresh=1) #saca los datos que tienen menos de 2 nan

Edad  Altura  Peso
Camilo   0.0     1.0   NaN
Edison   1.0     2.0   2.0
Oscar    NaN     3.0   NaN

In [96]:
datos.fillna(0,inplace=True)
datos #los datos con nan se convierten en 0

Edad  Altura  Peso
Camilo     0.0     1.0   0.0
Edison     1.0     2.0   2.0
Oscar      0.0     3.0   0.0
Patricia   0.0     0.0   0.0